### ISSUE TITLE
Phage prediction tools to include

### ISSUE THREAD

**Issue by replikation** [replikation/What_the_Phage#1]
# List of Tools 

## Implement?

* [VirMiner(Mining, analyzing, and integrating viral signals from metagenomic data)](https://github.com/TingtZHENG/VirMiner/)
  * [Paper](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-019-0657-y)
  + [ ] Docker file created
* [VirMine (viral sequences from metagenomes)](https://github.com/thatzopoulos/virMine)
  * [Paper](https://europepmc.org/articles/pmc6462185)
  * docker available, however, a full pipeline that also does read qc and assembly (spades)
  * but users can supply either raw Illumina sequencing reads (single-end or paired-end) or assembled contigs/scaffolds
   + [ ] Docker file created
* [PhaMers (Phage k-mers)](https://github.com/jondeaton/PhaMers)
  * [Paper](https://www.biorxiv.org/content/biorxiv/early/2017/07/28/169672.full.pdf)
  * input: `dir` where `fasta-file | *.fasta` is located
  * output: dir: `phamer_output/phamer_scores.csv`
  * **no database**
   + [ ] Docker file created

* [PhiSpy](https://github.com/linsalrob/PhiSpy)
  * [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3439882/)
  * [phispy support](https://github.com/JFsanchezherrero/PhiSpy)
   + [ ] Docker file created
* [FastViromeExplorer](https://github.com/saima-tithi/FastViromeExplorer)
    * [paper](https://peerj.com/articles/4227/)
    * `paired end ?`
    * **databse needed** see [link](https://bench.cs.vt.edu/FastViromeExplorer/)
     + [ ] Docker file created
* __ViromeScan__ ?

* vConTACT could be interesting to run on final selected putative phage contigs
https://peerj.com/articles/3243/
* Virminer

## Prophage-tools
* Phaster
* Virsorter
* Phage_Finder
* ProphET
* Prophinder
* PhiSpy
* uv ?? phiweger

## other interesting tools
* [v.HULK](https://github.com/LaboratorioBioinformatica/vHULK)

## Not possible to implement
* [Pro-Hunter](https://pro-hunter.bgi.com/) --> **no CLI ?**
  * [paper](https://academic.oup.com/nar/article/47/W1/W74/5494712)

**Comment by hoelzer** [comment]
I added VirMine to the list, just read the paper and sounds interesting

**Comment by hoelzer** [comment]
@replikation @Stormrider935 I just found VIBRANT and added it to the tool list. sounds very promising from what I screened from the preprint:

https://www.biorxiv.org/content/10.1101/855387v1

**Comment by replikation** [comment]
alright :)

**Comment by hoelzer** [comment]
added VirMiner (now there is a tool called VirMine and another called VirMiner - nice -.-)

**Comment by hoelzer** [comment]
vConTACT could be interesting to run on final selected putative phage contigs
https://peerj.com/articles/3243/

**Comment by mult1fractal** [comment]
new tool: [seeker](https://github.com/gussow/seeker)

**Comment by replikation** [comment]
@mult1fractal, seeker seems to be easily implemented, you could add that to the first post and open a low prio issue or?

**Comment by replikation** [comment]
* reference to #75

**Comment by mult1fractal** [comment]
## Pro-phage tools: 
* Phaster
* Virsorter
* Phage_Finder
* ProphET
* Prophinder
* PhiSpy

**Comment by phiweger** [comment]
uv (by me)

**Comment by hoelzer** [comment]
instead of `PhaMers` I would suggest to implement `PhaMer` as suggested here #155
