### ISSUE TITLE
Persistent errors with chromomap

### ISSUE THREAD

**Issue by sjspielman** [replikation/What_the_Phage#102]
Hello, 

I have been experiencing persistent errors specifically running the chromomap step - 
`[c6/5fb1e3] process > phage_annotation_MSF:chromomap (1)           [100%] 2 of 2, failed: 1...`
And ending with,
`[4e/57d82d] NOTE: Process 'phage_annotation_MSF:chromomap (1)' terminated with an error exit status (1) -- Execution is retried (1)`
Is there a known issue with chromomap at this time? I would be happy to provide any log files, though I'm not sure where to find those in the output. I have been running the workflow as suggested in the README (with my files indicated, too big to attach here..)
`nextflow run replikation/What_the_Phage --fasta 5_S31_assembly.fasta --cores 20 -profile local,docker -r v0.8.0 --output 5_S31_wtph`

Thanks for any feedback for how to get this working!

-Stephanie

**Comment by replikation** [comment]
Hi @sjspielman , thanks for the interest in WtP :)

The workflow works as intended. we included a few "failsafe" processes for chromomap, so if one plotting approach fails it retries another approach to render it, thus you get the fail but the retry should work. so I think you have the chromomap plots in your result dir?

**Comment by sjspielman** [comment]
Hi @replikation, 

Thanks for your reply. I do see some html output in the results directory. If this is what I was missing, then I guess it's all set! Along these lines, I'm wondering if you have additional documentation (perhaps some I missed!) for the files in the results directory? Or, some more explicit information for which output comes from which program so I can refer to their docs?

Thanks!!
-Stephanie

**Comment by replikation** [comment]
* hi, yes we will add that to the Readme and keep you informed when its done
