### ISSUE TITLE
Deprecation warning for unwrapped module inclusion

### ISSUE THREAD

**Issue by papanikos** [replikation/What_the_Phage#104]
Hello,

Thank you for this effort!

Currently, when launching the pipeline I get a 
```
WARN: Unwrapped module inclusion is deprecated -- Replace `include checkV from './MODULE/PATH'` with `include { checkV } from './MODULE/PATH'`
<truncated output>
```
for all modules included in the master `phages.nf`.

I am on `nextflow 20.07.1.5412` and using  release `v0.8.2`.

I wonder if I am the only one and if not, it seems like an "easy fix" (no idea how deep it goes into all the `nextflow` files :smiley:  ).

It is just a warning, and doesn't affect the execution, but for a nicer user experience, might be good to future proof?

**Comment by mult1fractal** [comment]
Thanks for your Issue Report!

I already took care of this in a PR for #98 
I will perform a testrun tonight and if there is no error we will release a new Version tomorrow (where this warning is fixed ;) )

**Comment by papanikos** [comment]
Sounds good! Feel free to close this now or after the PR has been merged
