### ISSUE TITLE
problem when installing WTP in a centralized way for multi-users

### ISSUE THREAD

**Issue by mandiayba** [replikation/What_the_Phage#106]
We wanted help to find solutions to setup a centralized multi-user installation of WtP ?

We have tried to install WtP in our cluster environment but we encountered some problems. 
We have tried to deploy one instance of WtP and to let our users (several users) run it from their individual accounts (e.g., via ssh connection). For that we have created special locations (shared locations) where to store the singularity images, the databases and the cache. Our idea was to let each run of WtP (from a user) use the shared locations but the usage you have provided forces our users to specify params `--workdir`, `--databases` and `--cache`, which is not very convenient in our case (we wanted the shared locations to be transparent to the users, to be set by default).
We have tried to specify the shared locations into the config file [nextflow.config](https://github.com/replikation/What_the_Phage/blob/master/nextflow.config) but that solution doesn't work since the WtP repo is pulled during execution. WtP repo is downloaded into {HOME}/.nextflow/ and we don't know how to change that location and modify the config file on the fly. We thought about using a fork but it will be difficult to maintain with the future developments of WtP. 
We haven't had time to investigate the question but we also suspected some conflicts when several runs are trying to access (likely write access) to the shared locations.

**Comment by replikation** [comment]
hi, 
thanks for the interest in WtP

if i understand this correctly you want "hardcoded" default settings?

**Quick Solution:**
* can't you just "install" WtP via `git clone --branch v0.9.0 https://github.com/replikation/What_the_Phage.git`
* then change the nextflow config and let the user use this "git"?  (the version would then be fixed to the git clone of course)
* e.g.:
````bash
./phage.nf \
  --fasta /path/to/file.fa \      # provide a fasta-file as input
  --cores 8 \                     # number of cores you want to use
  -profile local,docker           # choose the environment:local and docker
````

* would this help?

**something we could implement**
* otherwise I think nextflow supports an additional "nextflow config input" to e.g. store default data.
* would work like this (I think) : WtP would check the `$USER:~` if a "WtP_cluster.config" is available and add these parameters as default to the execution

**Comment by mandiayba** [comment]
Thank you for the very quick answer. 
Yes we want be able to set the default settings
and by that allow several running instances of WtP to use the same workdir, the same databases and same cachedir without conflicts.

We will try the "Quick Solution", it is probably the solution.

and yes, something like "additional config input" to add to `.bashrc` file or somewhere else (for example via environment variables) will be helpful in our case.

**Comment by replikation** [comment]
@mandiayba there seems to be a nextflow builtin for your issue that I was not aware of yet.

* you can "distribute" top-level congfis via `-params-file`
* see section 4 of [this blog](https://www.nextflow.io/blog/2020/cli-docs-release.html)
* so you could provide a yml file with all the paths and params and add this to the what the phage run command via e.g. `-params-file config.yml`
* @mult1fractal  we should test that and just add this part to the readthedocs

**Comment by mandiayba** [comment]
@replikation thank you.

**Comment by mult1fractal** [comment]
No time to check it yet.. is on my to do stack for next week
