### ISSUE TITLE
supervenn as an alternative/complement to UpsetR

### ISSUE THREAD

**Issue by papanikos** [replikation/What_the_Phage#110]
Hi,

What do you guys think of this? I personally find it a bit more legible than UpsetR.

https://github.com/gecko984/supervenn

This could be added as an extra plot or the user can choose which one to produce.

**Comment by replikation** [comment]
hi, thanks for the suggestions, which of the one in the linked git do you mean?

**Comment by papanikos** [comment]
For a biological example this:

https://github.com/gecko984/supervenn#banana-genome-compared-to-5-other-species

In general, I meant this as another tool to visualize multiple intersecting sets. An example figure I 've made for some of my data when trying some stuff out 

![image](https://user-images.githubusercontent.com/12234813/96984295-b5502f80-1520-11eb-8bb4-01e5ebe5f913.png)

**Comment by replikation** [comment]
* probably comes down to preferences as this is basically the upsetR figure "flipped" and the bar charts reduced to numbers and the dots changed to colors representing the size
* we will keep this issue open and add this besides the upsetR figure at a later point ( we have a few more high priority issues to solve currently ;)  )

thanks for the suggestion :)
