### ISSUE TITLE
Using own checkV_database

### ISSUE THREAD

**Issue by ibelalov** [replikation/What_the_Phage#113]
WtP is trying to download checkV_database. For some reasons  https://portal.nersc.gov/ is not accessible to me (... failed: Connection timed out). May be this is because I am in Russia now. I have checkV_database on my computer with CHECKVDB in my path. How do I tell WtP to use local checkV_database and not downloading it? Placing the folder into 'nextflow-autodownload-databases' folder does not work either.

**Comment by ibelalov** [comment]
Solved it myself. Placing the DB into 'nextflow-autodownload-databases should look like: "/nextflow-autodownload-databases/checkV/checkv-db-v0.6"

**Comment by mult1fractal** [comment]
Hey,

uploaded the databases yesterday to [OSF](https://osf.io/wtfrc/) in case some autodownload links won't work.
You can try to download the specific CheckV folder from OSF and copy it in your nextflow-autodownload-databases, but I wasn't able to test the download yet (will do it on monday)

the folder structure for CheckV-db in the nextflow-autodownload-databases should look like this:
```bash
nextflow-autodownload-databases:
  CheckV
   checkv-db-v0.6
     genome_db
     hmm_db
     README.txt
```

**Comment by replikation** [comment]
we will also do direct osf downloads for the next release
