### ISSUE TITLE
Reducing the number of files?

### ISSUE THREAD

**Issue by deminatanja** [replikation/What_the_Phage#116]
Hi,
I have been running What-the-Phage pipeline on a metagenome of about 20 Gb, and during the job running, millions of files have been created in the workflow-phages-username directory. I have a limit of 10 mil files on my server disk area, and the job stopped when about 9.8 mil files were produced, which reached the total limit together with other files I have on the disk. Is there any way to reduce the number of files during the run? It is quite problematic to receive more disk quota from the server admins. Would using the initially smaller dataset help to reduce the number of produced files?
Best regards,
Tatiana

**Comment by replikation** [comment]
hi

## solution 1  (deactivate marvel)
* add `--ma` to remove marvel from the analysis - this uses a split fasta commands and produces as many files as contigs are present
* we will add some remove commands to this to reduce the foodprint of this process in the future :)

## solution 2 (should work for you)
* you can do both steps separatly (identification and annotation) to clean up inbetween 
    * first identify only via  `--identify` flag 
    * afterwards use the identified sequences as input and do annotation only via  `--annotate`

## solution 3 (untested)
* removing temporary files while running is still an open issue in the workflow manager (https://github.com/nextflow-io/nextflow/issues/452)
    * I did a test runs adding  `-process.scratch true` to the whole WtP command which should remove unneeded files during execution
    * however sourmash failed and was not included in the results 
    * (did not yet have results on the annotation part)

**Comment by deminatanja** [comment]
Hi, thank you, solution 1 helped to get the job done!

**Comment by replikation** [comment]
@mult1fractal i add this issue to the todo we might want to "check input data" if there are "to many contigs" and auto deactivate marvel (?) or atleast add this to our FAQ documentation

@deminatanja how many contigs or sequences has you input file? (`grep ">" -c *.fasta`)

**Comment by deminatanja** [comment]
> @deminatanja how many contigs or sequences has you input file? (`grep ">" -c *.fasta`)
The metagenome I used when the problem of too many files occurred had 9,096,281 contigs. Later I updated the WtP version  and switched to smaller datasets of about 1,200,000 contigs with --ma option, and the jobs ran without problems.
