### ISSUE TITLE
Included bioinformatic tools on readme page

### ISSUE THREAD

**Issue by bramvandijk88** [replikation/What_the_Phage#117]
Since the last change in the readme, i can' t find back the table that used to be here: https://github.com/replikation/What_the_Phage#included-bioinformatic-tools

**Comment by mult1fractal** [comment]
Hey,
We updated our Readme  to a read-the-docs-style [here](https://mult1fractal.github.io/wtp-documentation/) so it is more lucid.
At the bottom of the "home" page you will find the table with the included tools
