### ISSUE TITLE
improve readme prior abstract submission

### ISSUE THREAD

**Issue by replikation** [replikation/What_the_Phage#12]
@Stormrider935 

add a installation manual to the readme.

# simple install
sudo Java runtime
sudo docker
usermod docker
wget nextflow

**Comment by Stormrider935** [comment]
# how to install and run your first sample 
### how to install java
### where to get docker + installation; just c&p
### where to get nextflow + installation just c&p
### example for own sample

**Comment by Stormrider935** [comment]
README.md updated!

**Comment by replikation** [comment]
okay Readme looks good. closing this
