### ISSUE TITLE
maximal CPUs incorrect

### ISSUE THREAD

**Issue by smdabdoub** [replikation/What_the_Phage#120]
I don't know if this is a nextflow issue, but [line 7 in nextflow.config](https://github.com/replikation/What_the_Phage/blob/465df50a81d03a85853431dff8448262e8dc22bb/nextflow.config#L7) returns 1 for max_cores. So when running the setup I get the following line:

`CPUs to use: 40, maximal CPUs to use: 1`

and frequent errors like:

    Error executing process > 'setup_wf:vibrant_download_DB'
    
    Caused by:
      Process requirement exceed available CPUs -- req: 4; avail: 1

I'm still running the setup, but manually setting it to the correct value seems to be working so far...

**Comment by mult1fractal** [comment]
Hey, thanks for your feedback!
We will check this.

Yes.. with `--cores 4` you should be able to solve this Problem. But we will fix this in our next update 👍🏼

**Comment by replikation** [comment]
@smdabdoub you should be able to increase this via e.g. `--max_cores 20`
@mult1fractal we might want to hard code a high number in there? not sure

**Comment by hoelzer** [comment]
Hi @smdabdoub and thanks for reporting!

It looks like `max_cores = Runtime.runtime.availableProcessors()` does not get the correct number of cores on your system so this can be solved as @replikation suggested. 

However, what is the machine you are running the pipeline on? A cluster machine? Work station? 

The reason we implemented this: imagine you have a single workstation with 48 cores that are used by many users. Now, someone runs WtP and blocks all cores on the machine. Per default, all available cores should be used but this can be adjusted via `--max_cores`.

**Comment by replikation** [comment]
we should move this parameter to the local profile then? @hoelzer

**Comment by hoelzer** [comment]
> we should move this parameter to the local profile then? @hoelzer

True, the parameter is only useful in local execution mode. Cloud and HPC (Slurm, ...) should be not affected. But I think this is also already implemented only for the local profile:
https://github.com/replikation/What_the_Phage/blob/master/nextflow.config#L89

**Comment by smdabdoub** [comment]
@replikation Thank you, the --max_cores flag worked!

@hoelzer I'm running this on a cluster node, so I'm using all available cores.

**Comment by hoelzer** [comment]
> @replikation Thank you, the --max_cores flag worked!
> 
> @hoelzer I'm running this on a cluster node, so I'm using all available cores.

Good to hear that it works now! May I ask which `-profile` configuration you are using on your cluster node? If you are using something like `-profile local,singularity` it seems that the `availableProcessors` command does not work on your cluster node. If you are using an HPC scheduler such as `-profile slurm,singularity` the max cores parameter should have no effect.

**Comment by smdabdoub** [comment]
@hoelzer I haven't figured out how to configure the SLURM side of the WtP, so I've been starting SLURM jobs myself and then using `-profile local,singularity`.

**Comment by replikation** [comment]
@smdabdoub WtP is autoconfigured to submit each task with the appropriate CPU ram. did you try running it via `-profile slurm,singularity` ? it submits a slurm job for each process basically.

* slurm was integrated and tested, check this: https://github.com/replikation/What_the_Phage/pull/84

**Comment by hoelzer** [comment]
> 
> 
> @hoelzer I haven't figured out how to configure the SLURM side of the WtP, so I've been starting SLURM jobs myself and then using `-profile local,singularity`.

Ahh, okay so you submitted the whole pipeline call (`nextflow run phage.nf ...`) via sbatch and `-profile local,singularity`? That way, WtP will only run on a single node on your Slurm HPC and does not take advantage of parallelization like described by @replikation . Depending on your sbatch command, it might even start a node only with 1 core per default and that's why the auto-check for the maximum number of cores only detected 1 CPU.

**Comment by smdabdoub** [comment]
@replikation I did attempt using `-profile slurm,singularity` but the scheduler threw an error complaining that no available resources matched the request. I'm assuming I need to edit the default nextflow.config [SLURM section](https://github.com/replikation/What_the_Phage/blob/ad372f0f7dd49e408a30260805d948a2ae0e7088/nextflow.config#L68).

@hoelzer If I can get the SLURM configuration working, I would definitely prefer that. But in the meantime, I've been running interactive jobs using salloc with --nodes=1 --ntasks=40, so I'm definitely getting more than 1 core.

**Comment by replikation** [comment]
@smdabdoub yep this needs to be edited, if you can get this to work please report back and we try to add this. otherwise, I don't have experience with slurm to help here.
