### ISSUE TITLE
package checkv results in final output results

### ISSUE THREAD

**Issue by papanikos** [replikation/What_the_Phage#124]
Hello,

According to the `checkv.nf` there are several calls to checkv's functionality. However, I am only getting the final summary stats for quality in the `<prefix>_contigs_quality_summary.tsv` .

The rest of the `tsv`s and `viruses.fna` can be traced back to the workdir of the `checkv_wf` job, but this seems a bit convoluted and not secure - I like to remove the workdir after a complete execution since it grows **big**.

These files can be quite helpful if one is interested in finding regions, prophages etc.

I believe it would make sense to also bundle them together in a `results/raw_data/checkv_results_<prefix>.tar.gz`, similar to the rest of the tools output.

**Comment by replikation** [comment]
* seems resonable to add this `results/raw_data/checkv_results_<prefix>.tar.gz`
* thanks for the suggestions we keep ypu updated
