### ISSUE TITLE
Conda Installation - fails

### ISSUE THREAD

**Issue by kullrich** [replikation/What_the_Phage#125]
As given by the docu, the following fails:
conda create -n wtp nextflow==20.07.01 singularity==3.6
singularity 3.6 just does not exist
Could you please update the following page for the conda section and alter into
singularity==3.6.1
https://mult1fractal.github.io/wtp-documentation/installation/quick_installation/
Thank you in anticipation

**Comment by mult1fractal** [comment]
Hey,
Thanks for the feedback!

I updated the section to `singularity==3.6.1`
