### ISSUE TITLE
failed for  downloading the images

### ISSUE THREAD

**Issue by mol529** [replikation/What_the_Phage#128]
Hello,

I installed the tool via conda, and tried to download the images many times. However, all failed.

Command: nextflow run replikation/What_the_Phage -r v1.0.1 --setup -profile local,singularity --cachedir IMAGE-LOCATION

log:
N E X T F L O W  ~  version 20.07.1
Launching `replikation/What_the_Phage` [marvelous_swirles] - revision: 4d9ffa2b8a [v1.0.1]
_____ _____ ____ ____ ___ ___ __ __ _ _
  __      _______________________
 /  \    /  \__    ___/\______   \
 \   \/\/   / |    |    |     ___/
  \        /  |    |    |    |
   \__/\  /   |____|    |____|
        \/
_____ _____ ____ ____ ___ ___ __ __ _ _

Profile: local,singularity

Current User: mol
Nextflow-version: 20.07.1
WtP intended for Nextflow-version: 20.01.0
Starting time: 24-07-2020 15:18 UTC
Workdir location [--workdir]:
  /tmp/nextflow-phages-mol
Output location [--output]:
  results
Database location [--databases]:
  nextflow-autodownload-databases
Singularity cache location [--cachedir]:
  IMAGE-LOCATION

  WARNING: Singularity image building sometimes fails!
  Please download all images first via --setup --cachedir IMAGE-LOCATION
  Manually remove faulty images in IMAGE-LOCATION for a rebuild

CPUs to use: 8, maximal CPUs to use: 18

executor >  local (9)
executor >  local (9)
[21/275b61] process > setup_wf:setup_container (1)                       [  0%] 0 of 1
[12/0cfbf1] process > setup_wf:phage_references:download_references      [  0%] 0 of 1
[-        ] process > setup_wf:phage_blast_DB:phage_references_blastDB   -
[bb/2ec5a9] process > setup_wf:ppr_dependecies:ppr_download_dependencies [  0%] 0 of 1
[-        ] process > setup_wf:sourmash_database:sourmash_download_DB    -
[dd/2975c0] process > setup_wf:vibrant_download_DB                       [100%] 1 of 1, failed: 1 ✘
[34/812863] process > setup_wf:virsorter_database:virsorter_download_DB  [  0%] 0 of 1
[skipped  ] process > setup_wf:vogtable_database:vogtable_DB             [100%] 1 of 1, stored: 1 ✔
[2e/0c0bcc] process > setup_wf:pvog_database:pvog_DB                     [  0%] 0 of 1
[09/167e43] process > setup_wf:vog_database:vog_DB                       [  0%] 0 of 1
[35/bb59f3] process > setup_wf:rvdb_database:rvdb_DB                     [  0%] 0 of 1
[ea/ed5934] process > setup_wf:checkV_database:download_checkV_DB        [  0%] 0 of 1
[skipping] Stored process > setup_wf:vogtable_database:vogtable_DB
Pulling Singularity image docker://multifractal/vibrant:0.5 [cache /lustre/home/mol/wtp/IMAGE-LOCATION/multifractal-vibrant-0.5.img]
Error executing process > 'setup_wf:vibrant_download_DB'

Caused by:
  Process `setup_wf:vibrant_download_DB` terminated with an error exit status (1)

Command executed:

  # profile names for VIBRANT_setup.py
  cp -r /opt/conda/share/vibrant-1.0.1/databases/profile_names .
  /opt/conda/share/vibrant-1.0.1/databases/VIBRANT_setup.py

  # pack together database
  mkdir database && mv *.{HMM,h3?} database
  cp /opt/conda/share/vibrant-1.0.1/files/VIBRANT*.{tsv,sav} database
  tar -czf database.tar.gz database/

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Convert SIF file to sandbox...
  ERROR  : Failed to create user namespace: user namespace disabled

Work dir:
  /tmp/nextflow-phages-mol/dd/2975c0290d3eec0f1fac0bc23fb00b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by mult1fractal** [comment]
Hey @mol529 ,
Thanks for the feedback!

unfortunately I wasn't able to reproduce this error on our system...
Sometimes the servers where the databases are stored are down and WtP can't download the corresponding databases...
Please retry your command (it should work now)

if not....
I have already stored the databases needed for WtP on [OSF](https://osf.io/wtfrc/) so we become more independent...
You can download the databases from [here](https://osf.io/wtfrc/) 
The "database-failsafe" will come in an future update
