### ISSUE TITLE
Pipeline execution on a cluster using LSF schedule system and Singularity images

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#13]
I just wanted to give the pipeline a try here at the EBI server structure using Singularity and LSF to schedule jobs. I made a new branch and added the following profile to the configuration to get it ready to run:

````
  lsf {
        process.executor = 'lsf'
        singularity {
	    enabled = true
	    cacheDir = "/hps/nobackup2/singularity/mhoelzer"
	}
	workDir = "/hps/nobackup2/production/metagenomics/mhoelzer/nextflow-work-$USER"
        process {
	    cache = "lenient"
	    errorStrategy = "rerty"
	    maxRetries = 1
	    withLabel: virsorter { cpus = 24; memory = '24 GB'; container = 'multifractal/virsorter:latest' }
            withLabel: deepvirfinder { cpus = 24; memory = '24 GB'; container = 'multifractal/deepvirfinder:latest' }
            withLabel: marvel { cpus = 24; memory = '24 GB'; container = 'multifractal/marvel:latest' }
            withLabel: metaphinder { cpus = 24; memory = '24 GB'; container = ' multifractal/metaphinder:latest' }
            withLabel: pprmeta { cpus = 24; memory = '24 GB'; container = 'multifractal/ppr-meta:latest' }
            withLabel: r_plot { cpus = 4; memory = '4 GB'; container = 'replikation/r-phage-plot:latest' }
            withLabel: ubuntu { cpus = 4; memory = '4 GB'; container = 'ubuntu:bionic' }
            withLabel: virfinder { cpus = 24; memory = '24 GB'; container = 'multifractal/virfinder:latest' }
} }
````
The pipeline starts well but I get problems while pulling the docker images and converting them to singularity images:

````
Error executing process > 'metaphinder_wf:metaphinder (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name \ multifractal-metaphinder-latest.img docker:// multifractal/metaphinder:latest > /dev/null
  status : 255
  message:
    WARNING: pull for Docker Hub is not guaranteed to produce the
    WARNING: same image on repeated pull. Use Singularity Registry
    WARNING: (shub://) to pull exactly equivalent images.
    ERROR: Unknown container build Singularity recipe format: multifractal-metaphinder-latest.img
    ABORT: Aborting with RETVAL=255
    ERROR: pulling container failed!
````

I think this could be related to no tags are used for the docker images. There seems to be some issue with simply using ``:latest`` when converting docker images to singularity images. 

I totally understand that this is not your main focus now, but getting the workflow running also on cluster systems with a job scheduler like LSF and SIngularity support might be helpful in the future (and also interesting for some potential users). 

I am not entirely sure, but this might be fixed by simply tagging your Docker images on DockerHub.

**Comment by hoelzer** [comment]
Haha, forget it, it seems the problem was an empty space in the container definition :) 

````
withLabel: metaphinder { cpus = 24; memory = '24 GB'; container = ' multifractal/metaphinder:latest' }
````
But now I get an 

````
Execution aborted due to an unexpected error
````

and will further investigate this ;) 

But it seems that the docker image was converted now correctly to a singularity image.

**Comment by replikation** [comment]
@hoelzer okay so it is not the `:latest` image?
* `unexpected error`  ... wow super helpful :dancer: 
* okay, interesting, you can go lower on CPU I think. they are usually quite fast
* adding this config would be great, can also be easily converted to cloud then

**Comment by hoelzer** [comment]
@replikation 

yeah, I will try to figure out what's going on and if I get it working I can also merge the configuration.

**Comment by hoelzer** [comment]
Due to the really meaningful error message: "Execution aborted due to an unexpected error" I tried to figure out which module(s) is(are) causing trouble by executing the pipeline step-wise. 

&#x2714; VirSorter
&#x2714; VirFinder
X PPRmeta
&#x2714; metaphinder
X marvel
&#x2714; deepvirfinder  

Ad PPRmeta:
````
[skipped  ] process > ppr_dependecies:ppr_download_dependencies [100%] 1 of 1, stored: 1 ✔
[52/5d837b] process > pprmeta_wf:input_suffix_check (1)         [100%] 1 of 1, cached: 1 ✔
[54/172672] process > pprmeta_wf:pprmeta (1)                    [100%] 1 of 1 ✔
[-        ] process > pprmeta_wf:filter_PPRmeta                 -
[-        ] process > r_plot                                    -
Execution aborted due to an unexpected error
````

Ad MARVEL
````
[4a/edf457] process > marvel_wf:input_suffix_check (1)         [100%] 1 of 1, cached: 1 ✔
[bb/5e1b35] process > marvel_wf:marvel (1)                     [100%] 1 of 1 ✔
[-        ] process > marvel_wf:filter_marvel                  -
[-        ] process > r_plot                                   -
[skipping] Stored process > virsorter_database:virsorter_download_DB
Execution aborted due to an unexpected error
````

@replikation @Stormrider935 any ideas?

**Comment by hoelzer** [comment]
I just checked for MARVEL and the ``resuts.txt`` file is empty. I think that's already a problem.

**Comment by replikation** [comment]
@hoelzer  can you attach me the files of each process? I mean the log, err files etc. (the nextflow files within each process)

**Comment by replikation** [comment]
both processes are the only tools with additional databases and dependencies, either remove these "stored" files, so they are "fresh", or we need to figure out why they are not used.

**Comment by hoelzer** [comment]
I will delete the "stored" files, execute MARVEL and PPRmeta again and then add the files here.

**Comment by replikation** [comment]
can you also check if these "stored" files exist?

**Comment by hoelzer** [comment]
You mean in 'nextflow-autodownload-databases'? 

There I only have folders for

* pprmeta
* virsorter

**Comment by replikation** [comment]
yes exactly.

Sourmash/busco was working? (the other pipelines of nz) via lsf and singularity? because they also use storeDir for the databases. And mitos also

**Comment by replikation** [comment]
I currently think there might be a proper/stable way of handling DBs. Because it worked in some cases for you. We just need to figure out which is the best approach

**Comment by hoelzer** [comment]
Hm yes you are right, but I think I manually adjusted the database storage folder for the LSF cluster.  I used a configuration similar to our cloud configurations. Let me check, I will adjust the config profile and try it again.

**Comment by replikation** [comment]
and the 2 folders `pprmeta` and `virsorter` contain files?

**Comment by hoelzer** [comment]
yeah they contained files

**Comment by replikation** [comment]
okay because i noticed that the dependencies of these are labeled with `label 'noDocker'`

**Comment by replikation** [comment]
could it be that these have to be executed in a docker also?

**Comment by hoelzer** [comment]
oh! Yeah that could be also the problem. Where is this defined? in the modules itself?

**Comment by replikation** [comment]
```java
process ppr_download_dependencies {
        storeDir 'nextflow-autodownload-databases/pprmeta'
        label 'noDocker'    
      output:
        file("PPR-Meta")
      script:
        """
        git clone https://github.com/Stormrider935/PPR-Meta.git
        """
    }
```

**Comment by replikation** [comment]
you can add a config statment to them

**Comment by replikation** [comment]
withLabel noDocker

**Comment by hoelzer** [comment]
ok, but also virsorter had this noDocker label and this tool worked.

**Comment by replikation** [comment]
ah fuck :D

**Comment by replikation** [comment]
ah right its marvel and ppr meta....

**Comment by replikation** [comment]
they both have `cp` statments. otherwise i probably need to see the log files were it fails.

**Comment by hoelzer** [comment]
ok I am now at PPRMeta. I added the noDocker abricate config as mentioned above and the database seems to be downloaded into nextflow-autodownload-databases, then:

````
[79/629d4c] process > ppr_dependecies:ppr_download_dependencies [100%] 1 of 1 ✔
[6a/ed7534] process > pprmeta_wf:input_suffix_check (1)         [100%] 1 of 1 ✔
[8a/20658c] process > pprmeta_wf:pprmeta (1)                    [100%] 2 of 2, failed: 2 ✘
[-        ] process > pprmeta_wf:filter_PPRmeta                 -
[4c/a4fec0] NOTE: Process `pprmeta_wf:pprmeta (1)` terminated with an error exit status (127) -- Execution is retried (1)
Error executing process > 'pprmeta_wf:pprmeta (1)'

Caused by:
  Process `pprmeta_wf:pprmeta (1)` terminated with an error exit status (127)

Command executed:

  cp PPR-Meta/* .
  ./PPR_Meta T7_draft.fa T7_draft.csv

Command exit status:
  127

Command output:
  (empty)

Command error:
  ./PPR_Meta: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory

Work dir:
  /hps/nobackup2/production/metagenomics/mhoelzer/nextflow-work-mhoelzer/8a/20658c12e504b6263e3952201b6306

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
````

**Comment by hoelzer** [comment]
H, but manually executing the image and running 

````
./PPR_Meta T7_draft.fa T7_draft.csv
````

from within the container works...

**Comment by hoelzer** [comment]
For MARVEL I get now:

````
  .command.sh: line 5: marvel_bins.py: command not found
````

It looks like there is again something weird with starting the correct singularity images. I will delete them again and try to pull them now with the 1.0 tag added by @Stormrider935

**Comment by replikation** [comment]
iam wondering with these singularity container. is it maybe better to build them yourself, or how is it actually working?

**Comment by replikation** [comment]
btw you can run this probably locally. its not that heavy ;)

**Comment by hoelzer** [comment]
> iam wondering with these singularity container. is it maybe better to build them yourself, or how is it actually working?

yeah, don't know exactly. SIngularity takes the docker image and translates it into a singularity image - somehow :)

**Comment by hoelzer** [comment]
> btw you can run this probably locally. its not that heavy ;)

yeah, a test sample just finished on my local machine, so that's working - nice work ;) 

However, I am eager to get it also running on the cluster... hmm

**Comment by replikation** [comment]
i mean the additional singularity know-how is nice. That's true

**Comment by hoelzer** [comment]
I close this issue and open two new ones for PPRMeta and MARVEL to figure out what is going on at the LSF cluster.
