### ISSUE TITLE
Prodigal output

### ISSUE THREAD

**Issue by deminatanja** [replikation/What_the_Phage#131]
Hi,
Do I understand correctly that the Prodigal output file (.../raw_data/prodigal_out/contigs_prodigal.faa) is for all positive contigs (i.e., from all tools)? Is there a way to extract only some part of the file that corresponds to e.g. just Virsorter-identified contigs? Or is the only way to produce such file is to take raw data from the tool of interest and run Prodigal separately?
Best regards,
Tatiana

**Comment by mult1fractal** [comment]
Hey @deminatanja 
correct, `.../raw_data/prodigal_out/contigs_prodigal.faa` is for all the tools that were deployed.

If you want a `.../raw_data/prodigal_out/contigs_prodigal.faa` for only eg. virsorter you could try this:
* turn off all tools except virsorter and run WtP
* you could also run WtP as usual but with `--identify`
  * get the raw data from virsorter 
  * run WtP with `--annotate` and the raw data from virsorter as input 
    *  Workflow control:
    `--identify`          only phage identification, skips analysis
    `--annotate`          only annotation, skips phage identification

hope this helps

**Comment by deminatanja** [comment]
Hi,
Thank you for the answer!
Best,
Tatiana
