### ISSUE TITLE
checkV output

### ISSUE THREAD

**Issue by ntromas** [replikation/What_the_Phage#135]
Dear WTP team,

Thanks for this excellent pipeline!
I played a bit with my dataset and I got 86 viral positive contigs. However, the output from checkV only found very few with viral gene. Is checkV too conservative? 

My second question concerns the prophage prediction, is there a way to separate potential viral contigs to potential prophage contigs?

Thanks!

Nico

**Comment by mult1fractal** [comment]
Hey @ntromas 
Thanks for the positive feedback!

1) We are running CheckV with default settings... but if you want to use different settings you can also use the docker container `nanozoo/checkv:0.6.0--e97f45e`
but make sure you start the container in the folder where the checkV database is located... or mount the database into the docker container.


2) We are currently working on a scoring system (probably in august as new release)... I will put your suggestion on my to do 👍🏽 
but for now: using the raw output from checkV
* via grep: get rows that are of interest for you (eg rows/contigs that are potential prophages)
* extract contig_names
* via samtools: extract sequences from your input based on the extracted contig_names 
(you can use the samtools docker if you don't want to install samtools on your PC `nanozoo/samtools:1.9--76b9270`)

Hope it helps!

Mike
