### ISSUE TITLE
install without root privilege

### ISSUE THREAD

**Issue by ucassee** [replikation/What_the_Phage#137]
Hi,

I want to install the wtp on HPC, but I can't get root privilege. Is there a way for me to install wtp and run it with PBS environment?

Thanks

**Comment by mult1fractal** [comment]
Hey,

unfortunately we have no access to PBS environment...
later I will prepare a nextflow profile where you can test it and report back if it works for you 👍🏽 

But you need docker or singularity installed.. maybe you can ask your IT department if they can install singularity?

**Comment by ucassee** [comment]
Hi,
If your new version can be install without root privilege, I CAN test it on the HPC with PBS environment.
