### ISSUE TITLE
How to get the version of tools that What the Phage used？ e.g. virsorter，virfinder etc.

### ISSUE THREAD

**Issue by marineLZ** [replikation/What_the_Phage#141]

**Comment by deminatanja** [comment]
Hi @mult1fractal ,
I used the tool in Feb 2023, were the versions still same at that time point? I am only interested in Virsorter2, PPR-Meta and DeepVirFinder. 
Best,
Tatiana

**Comment by mult1fractal** [comment]
Hey


VirSorter 2.2
PPR meta has no version (has no help function where I can read out the version)
deepvirfinder v1.0

If you want to check yourself you can check the link: https://github.com/replikation/What_the_Phage/blob/master/configs/container.config

and access in your terminal the docker like this:
`docker run --rm -it -v $PWD:/input papanikos/virsorter-2:2.2.1--fa935f8
`
then use the corresponding tool name: e.g. `virsorter -h` and check the tool version
 

I did not updated the tools yet.. but thats a good idea to do... I hope it wont break anything :D

**Comment by deminatanja** [comment]
Thanks a lot! :)
