### ISSUE TITLE
Error downloading VOGTable.txt

### ISSUE THREAD

**Issue by bramvandijk88** [replikation/What_the_Phage#142]
My What the Phage workflow is currently unable to access the following file. As you may notice, the file is just not available now. So I suspect has been moved or renamed: http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt

But the entire workflow now hangs. I however have the file available somewhere, but failed to figure out how to make the workflow use my local VOGtable file. How can I do this?

**Comment by replikation** [comment]
hi,

we have databases also backuped here: https://osf.io/wtfrc/

WtP has  a `--database` flag. you point with this flag to the "maindir" containing all the databases (each in their subdir). Like the backup structure here: https://osf.io/wtfrc/   to include these preloaded databases just do `--database WtP_Nextflow_databases`

**Comment by papanikos** [comment]
For anyone interested in downloading the osf-backed data from the command line 

I could not figure out a simple `wget` or `curl` method so I used the [osfclient](https://osfclient.readthedocs.io/en/stable/) You will need to install it either with
```
$ pip install osfclient
```
or
```
$ conda install -n wtp osfclient
``` 

Then
```
$ osf -p wtfrc clone databases
```
where `databases` is my desired local output path.

This gets stuff stored in  `databases/osfstorage/WtP_Nextflow_databases`, so move stuff around or use that dir with the `--databases` flag when running the workflow.
