### ISSUE TITLE
deactivate tools

### ISSUE THREAD

**Issue by marineLZ** [replikation/What_the_Phage#143]
I deactivate some tools in the command. But WTP still run all these tools and only get the "raw_data" file result.
My  code is: 
nextflow run ~/.nextflow/assets/replikation/What_the_Phage/phage.nf \
--fasta ./mix_all_filter.fa \
--output ./result_out \
--databases ~/nextflow-autodownload-databases \
--cachedir ~/singularity-images \
-profile local,singularity --work-dir work --cores 32 \
--dv \ 
--ma \
--mp \
--pp \
--sm \ 
--vb \ 
--vn \
--ph \ 
--vs2

**Comment by mult1fractal** [comment]
Hey could you run WtP with a release candidate
these are stable versions and work as intended.
The master branch is this week "under construction" bc I'm working on a simplification of the workflow.

```shell
cd ~/.nextflow/assets/

nextflow run replikation/What_the_Phage/phage.nf  -r v1.0.2
--fasta ./mix_all_filter.fa
--output ./result_out
--databases ~/nextflow-autodownload-databases
--cachedir ~/singularity-images
-profile local,singularity --work-dir work --cores 32
--dv \
--ma
--mp
--pp
--sm \
--vb \
--vn
--ph \
--vs2
```shell

**Comment by marineLZ** [comment]
Dear authors，when I add the version flag i.e. -r v1.0.2. An error occurred : Revision option cannot be used running a script.

**Comment by mult1fractal** [comment]
Hey,

have you tried it without the `.` behind the `2` ?
`nextflow run replikation/What_the_Phage  -r v1.0.2`

**Comment by marineLZ** [comment]
Yes， there is no . behind the 2.

N E X T F L O W  ~  version 20.07.1
Revision option cannot be used running a script

my commad are as follow: 

cd ~/.nextflow/assets
nextflow run replikation/What_the_Phage/phage.nf -r v1.0.2 \
--fasta ~/zhoulei/WTP-deepsea/mix_all_filter.fa \
--output ./result_out1 \
--databases ~/nextflow-autodownload-databases \
--cachedir ~/singularity-images \
-profile local,singularity --work-dir work --cores 32

or nextflow run replikation/What_the_Phage -r v1.0.2 \
--fasta ~/zhoulei/WTP-deepsea/mix_all_filter.fa \
--output ./result_out1 \
--databases ~/nextflow-autodownload-databases \
--cachedir ~/singularity-images \
-profile local,singularity --work-dir work --cores 32

**Comment by replikation** [comment]
this "Revision option cannot be used running a script" happens when you are directly using the `phage.nf` file ( so a local run) instead of 
`nextflow run replikation/What_the_Phage -r v1.0.2  --help`
