### ISSUE TITLE
phage_tax_classification process issue

### ISSUE THREAD

**Issue by ntromas** [replikation/What_the_Phage#144]
Hi!

I am using WTP with a very large input file of contigs (10,977,373 seq)

**Command used:** nextflow run replikation/What_the_Phage --fasta all_contigs_Champ_2016_2020.fa --cores 12  -r v1.0.2 --workdir work --cachedir cache -profile local,docker

**Error found (I repeated several time and always got this)**

Error executing process > 'vogtable_database:vogtable_DB'

Caused by:
  Process `vogtable_database:vogtable_DB` terminated with an error exit status (4)

Command executed:

  wget -nH http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt

Command exit status:
  4

Command output:
  (empty)

Command error:
  Retrying.
  
  --2021-09-13 14:34:46--  (try: 9)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:37:04--  (try:10)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:39:24--  (try:11)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:41:44--  (try:12)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:44:03--  (try:13)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:46:22--  (try:14)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:48:41--  (try:15)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:51:01--  (try:16)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:53:20--  (try:17)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:55:39--  (try:18)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 14:57:58--  (try:19)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Retrying.
  
  --2021-09-13 15:00:18--  (try:20)  http://dmk-brain.ecn.uiowa.edu/pVOGs/downloads/VOGTable.txt
  Connecting to dmk-brain.ecn.uiowa.edu (dmk-brain.ecn.uiowa.edu)|128.255.23.191|:80... failed: Connection timed out.
  Giving up.

Work dir:
  /mnt/1bcce214-6fb0-454a-99a7-df65602d98b6/What_the_Phage-master/work/f4/ceff45e1ed8c0f3222f5d9ed789304

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Have you ever seen this one?

Thanks for your help!

Nico

**Comment by mult1fractal** [comment]
hey,

this error was described in issue #142 
I already fixed it by directly downloading it by the OSF backup databases.
This fix will hopefully come this week as it is part of a bigger WtP rework.

sorry for the inconvenience

**Comment by ntromas** [comment]
Hey,

Thanks, I downloaded the database and use the --databases flag (on your doc, you describe it as --database, the "s" is missing).
Thanks!

**Comment by ntromas** [comment]
Hi!
With the downloaded db, it worked, thanks!
However, I got several errors. Not sure if the process for these virus pipelines worked or not.
Thanks for your help,

Nico


_[7c/a72104] NOTE: Process `identify_fasta_MSF:vibrant_virome_wf:vibrant_virome (1)` terminated with an error exit status (1) -- Error is ignored

I got the same for seeker and pprmeta (example of what I have)

[a4/65f607] process > identify_fasta_MSF:metaphin... [100%] 1 of 1 ✔
[71/b16714] process > identify_fasta_MSF:metaphin... [100%] 1 of 1 ✔
[9b/d5db1c] process > identify_fasta_MSF:metaphin... [100%] 1 of 1 ✔
[b3/69d629] process > identify_fasta_MSF:metaphin... [  0%] 0 of 1
[-        ] process > identify_fasta_MSF:metaphin... -
[-        ] process > identify_fasta_MSF:metaphin... -
[bd/805a47] process > identify_fasta_MSF:deepvirf... [100%] 1 of 1 ✔
[54/994a37] process > identify_fasta_MSF:deepvirf... [100%] 1 of 1 ✔
[47/be0905] process > identify_fasta_MSF:deepvirf... [100%] 1 of 1 ✔
[de/1a02f6] process > identify_fasta_MSF:virfinde... [  0%] 0 of 1
[-        ] process > identify_fasta_MSF:virfinde... -
[-        ] process > identify_fasta_MSF:virfinde... -
[28/7fba84] process > identify_fasta_MSF:pprmeta_... [100%] 1 of 1, failed: 1 ✔
[-        ] process > identify_fasta_MSF:pprmeta_... -
[-        ] process > identify_fasta_MSF:pprmeta_... -
[73/bbf69e] process > identify_fasta_MSF:vibrant_... [100%] 1 of 1 ✔
[9d/069d17] process > identify_fasta_MSF:vibrant_... [100%] 1 of 1 ✔
[37/6f39e8] process > identify_fasta_MSF:vibrant_... [100%] 1 of 1 ✔
[7c/a72104] process > identify_fasta_MSF:vibrant_... [100%] 1 of 1, failed: 1 ✔
[-        ] process > identify_fasta_MSF:vibrant_... -
[-        ] process > identify_fasta_MSF:vibrant_... -
[f2/19b23e] process > identify_fasta_MSF:virnet_w... [100%] 1 of 1 ✔
[-        ] process > identify_fasta_MSF:virnet_w... [  0%] 0 of 1
[-        ] process > identify_fasta_MSF:virnet_w... -
[-        ] process > identify_fasta_MSF:virnet_w... -
[49/60e3c2] process > identify_fasta_MSF:phigaro_... [100%] 1 of 1 ✔
[0c/9b2399] process > identify_fasta_MSF:phigaro_... [100%] 1 of 1 ✔
[4d/13d3c2] process > identify_fasta_MSF:seeker_w... [100%] 1 of 1, failed: 1 ✔_

**Comment by replikation** [comment]
hi, some tools sometimes cause errors (could be due to the input data) we set these to ignore so the pipeline continues.

**Comment by ntromas** [comment]
Hi!

Thanks, do you think it might be due to the big size of the input or the
computer capacity?

Nico

**Comment by replikation** [comment]
yep could be. you could try to set the `--cores` the amount of threads you have, thus spawning only one process after another (not multiples in parallel)
