### ISSUE TITLE
exit status (137)

### ISSUE THREAD

**Issue by ntromas** [replikation/What_the_Phage#151]
Hi,

I just got this error and I wonder how to fix it. Thanks for the help!
In the working dir "70c33636e9449f7ab62b01d9375d6e" I do have tmp_allctgs.txt file that is not empty.

Cheers 

Nico

_Error executing process > 'identify_fasta_MSF:samtools (1)'

Caused by:
  Process `identify_fasta_MSF:samtools (1)` terminated with an error exit status (137)

Command executed:

  cat metaphinder-own-DB.txt metaphinder.txt phigaro.txt seeker.txt sourmash.txt vibrant-virome.txt vibrant.txt virfinder.txt virsorter-virome.txt virsorter.txt virsorter2.txt | sort | uniq > tmp_allctgs.txt
  cat Preselection_dvf_filtered.fa > all.fasta
  
  # get samtools but ignore "samtool fails"
  while read fastaheader; do    
      if grep -qw ">$fastaheader" all.fasta; then
          samtools faidx all.fasta $fastaheader >> Preselection_dvf_positive_contigs.fa
      else
          echo "$fastaheader not found" >> error_code_samtools.txt
      fi
  done < tmp_allctgs.txt
  
  # old command
  # xargs samtools faidx all.fasta < tmp_allctgs.txt > Preselection_dvf_positive_contigs.fa

Command exit status:
  137

Command output:
  (empty)

Work dir:
  /mnt/1bcce214-6fb0-454a-99a7-df65602d98b6/What_the_Phage-master/work2/2e/70c33636e9449f7ab62b01d9375d6e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line_

**Comment by replikation** [comment]
hi, exit statements of 137 or more generally exit> 100 are usually related to the computer hardware (e.g. not enough RAM).

what system are you running on?

**Comment by ntromas** [comment]
Hi,

Worstation with Ubuntu 20.04 , 128Gb RAM, 26 cores.

Nico


Le lun. 8 nov. 2021 08 h 52, Christian Brandt ***@***.***> a
écrit :

**Comment by replikation** [comment]
can you also paste the command used and the WtP version that you used? @ntromas

**Comment by mult1fractal** [comment]
I'm running now your command on our workstation and try to reproduce the error.

**Comment by mult1fractal** [comment]
Hey,

I was unable to reproduce your error.
The workflow finished without any problems with your command.

Have you tried to reboot your workstation and re-run WTP

**Comment by ntromas** [comment]
Will try that...

Le mar. 9 nov. 2021 04 h 05, Mike Marquet ***@***.***> a
écrit :
