### ISSUE TITLE
virsorter2-db not working in v1.0.2

### ISSUE THREAD

**Issue by phageattack** [replikation/What_the_Phage#152]
I tried to use v1.0.2 
nextflow run replikation/What_the_Phage --no-check-certificate --setup -r v1.0.2 -profile local,singularity --databases /home/sguajardo/wtp_new_DB --workdir /home/sguajardo/wpt_workdir --cachedir wtp_cache

and I get this error:

Error executing process > 'setup_wf:virsorter2_download_DB'

Caused by:
  Process `setup_wf:virsorter2_download_DB` terminated with an error exit status (5)

Command executed:

  wget https://osf.io/v46sc/download -O db.tgz
  tar -zxvf db.tgz
  chmod -R a+rX db
  rm db.tgz

Command exit status:
  5

Command output:
  (empty)

Command error:
  --2021-12-05 17:21:43--  https://osf.io/v46sc/download
  Resolving osf.io (osf.io)... 35.190.84.173
  Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
  ERROR: cannot verify osf.io's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
    Issued certificate has expired.
  To connect to osf.io insecurely, use `--no-check-certificate'.

Work dir:
  /home/sguajardo/wpt_workdir/1e/234ad8507fbfd26eff318129b68829

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

So I have downloaded the database following this:
wget https://osf.io/v46sc/download -O db.tgz
tar -zxvf db.tgz
chmod -R a+rX db
rm db.tgz
And I moved the db directory to my databases directory. After that, I used -resume flag but still get the same error again.
What I´m doing wrong?
I also tried renaming the db to virsorter2-db with no success 

Thanks for any help

**Comment by mult1fractal** [comment]
could you try the command without `-resume` and  `--no-check-certificate` ?

**Comment by phageattack** [comment]
That sounds great! thanks.

**Comment by mult1fractal** [comment]
Hey,
I added the --no-check-certificate now to all wgets and released a pre-release: 

Can you try your command again with `-r v1.0.3` and test if the download works?

**Comment by phageattack** [comment]
Thaks for the quick fix!! but it gave me another error
Module compilation error
- file : /root/.nextflow/assets/replikation/What_the_Phage/./workflows/./process/input_validation/input_suffix_check.nf
- cause: Invalid process definition -- Unknown keyword `stub` @ line 36, column 9.
           """
           ^

**Comment by replikation** [comment]
@phageattack ah you are using an older nextflow version or? please update to a newer or the most recent one. stub is the dry run feature of newer nextflow versions we included for continuous integration
