### ISSUE TITLE
could not run wtp

### ISSUE THREAD

**Issue by quliping** [replikation/What_the_Phage#156]
Hollow, first, I have finished the "--setup" step and it seemed to be successful. Then, I tried to run wtp as follows:
nextflow run replikation/What_the_Phage -r v1.0.1 --cores 8 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta

However, it didn't work. The output is:
N E X T F L O W  ~  version 20.07.1
Pulling replikation/What_the_Phage ...
https://github.com/replikation/What_the_Phage.git: cannot open git-upload-pack

I also tried this:
phage.nf --cores 8 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta
and the outout is:
![image](https://user-images.githubusercontent.com/39583607/152086586-7d8e5778-74c4-48c4-832f-2f9edf70ae14.png)

and these two:
nextflow run phage.nf --cores 8 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta
nextflow run phage.nf -profile smalltest,local,docker --work-dir work --cores 16 ##This is the test run command on the website.
The output of both of them is:
N E X T F L O W  ~  version 20.07.1
Not a valid project name: phage.nf

It is the first time for me to use this sofware, and I have no idea. What's wrong?

**Comment by mult1fractal** [comment]
Hey ,

1. so first of all make sure you have the newest version of nextflow installed #152 (last three posts)
2.  run your command  with the pre-release
nextflow run replikation/What_the_Phage -r v1.0.3 --cores 8 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta

Please tell me if `cannot open git-upload-pack` persists.. I have not yet seen this error yet

For the last execution:
You need to execute the nextflow run command in the What_the_Phage directory
unfortunately I cannot see in which is your current working directory, but error occurs when usually when nextflow does not see `phage.nf`
You could run : nextflow run /foo/bar/phage.nf

**Comment by quliping** [comment]
Thanks for your suggestion. I installed the neweast version of nextflow and told the absolute path of phage.nf to nextflow: 
nextflow run /public/apps/What_the_Phage-master/phage.nf --cores 8 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta --no-check-certificate
Indeed, the old problem was gone.  

However, whatever I am using '--no-check-certificate' or not, it gave me a new error similar to this: https://github.com/replikation/What_the_Phage/issues/152 . Therefore I tried this command:

nextflow run replikation/What_the_Phage -r v1.0.3 --cores 8 -profile local,singularity --no-check-certificate
 --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta ./JM65_10-12cm.fasta

and the 'cannot open git-upload-pack' persists. Then I added '--setup' in this commond:

 nextflow run replikation/What_the_Phage -r v1.0.3 --cores 8 --setup -profile local,singularity --databases /public/data/database/wtp_database --workdir /public/work_dir --cachedir /public/cachedir --no-check-certificate

and it gave me an new error:

N E X T F L O W  ~  version 21.10.6
Unknown error accessing project `replikation/What_the_Phage` -- Repository may be corrupted: /root/.nextflow/assets/replikation/What_the_Phage

**Comment by replikation** [comment]
ehm seems that something might went wrong on you system will doing a regular download. can you please remove the whole dir here:
/root/.nextflow/assets/replikation/What_the_Phage
so that nextflow can redownload the whole git? because "Repository may be corrupted:" seems to be related to the local git

**Comment by quliping** [comment]
Thanks for your reply, and I have resolved all of these problems after downloading the pre-release version (v1.0.3) and runing as follows (Even I still could not run "nextflow run replikation/What_the_Phage -r v1.0.3", but it is ok now):

nextflow run /public/apps/What_the_Phage-1.0.3/phage.nf --cores 16 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork  --no-check-certificate --fasta ./JM65_10-12cm.fasta --output try-out

This command  worked and all databases were successfully set up. However, there are some new errors:

![image](https://user-images.githubusercontent.com/39583607/152680911-13e1e209-4219-4b10-b308-1692242825f0.png)
![image](https://user-images.githubusercontent.com/39583607/152680930-db278f47-8d10-46a7-a9d0-b1e52a1ce630.png)

**Comment by replikation** [comment]
Hey that's a singularity error while creating a singularity container. But
is related to singularity and not WtP seems to be a setup/configuration
issue of singularity

quliping ***@***.***> schrieb am So., 6. Feb. 2022, 13:38:
