### ISSUE TITLE
Vibrant and virsorter 2 generate duplicate rows for similar contig

### ISSUE THREAD

**Issue by mult1fractal** [replikation/What_the_Phage#157]
> library(tidyr)
> wide <- spread(dt, toolname, p_value)
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 2 rows:
* 256, 257

Full report will fail on both tools

**Comment by replikation** [comment]
the pain. is there a R solution for it? @AggresiveHayBale
do these row contain different information?

**Comment by AggresiveHayBale** [comment]
We discussed it with Mike and we think its better to solve it outside R and not put a new coat of paint on a bug that wasn't solved.
