### ISSUE TITLE
the conda installation problem of the newest version v1.1.0 

### ISSUE THREAD

**Issue by dangchenyuan** [replikation/What_the_Phage#160]
Hi, 
When I installed the newest version v1.1.0 via conda command "nextflow run replikation/What_the_Phage -r v1.1.0 --setup ...", the error was shown "Cannot find revision `v1.1.0` -- Make sure that it exists in the remote repository `https://github.com/replikation/What_the_Phage`."
But when I changed to v1.0.3, it worked.

**Comment by lingyi-owl** [comment]
I have the same issue and I want to use version v1.1.0. Can the developer help with us?

**Comment by mult1fractal** [comment]
Hey,

have you tried:
`nextflow pull replikation/What_the_Phage`

then:
`nextflow run replikation/What_the_Phage -r v1.1.0 --setup ...`

**Comment by mult1fractal** [comment]
yes that would have been my next suggestion...
unfortunately do not use conda at all and only work with Docker

**Comment by dangchenyuan** [comment]
> just tried it, and it showed:
> 
> ```
> $nextflow pull replikation/What_the_Phage
> Checking replikation/What_the_Phage ...
> done - revision: fc18d6a2a6 [v1.0.2]
> ```
> 
> I will try to install the environment again using Conda and see what happens

re-install seems not to work, since I have re-installed several times.

**Comment by mult1fractal** [comment]
okay 
quick fix:
go to your `What_the_Phage repo` - `git pull`
execute the workflow in the repo
`nextflow run phage.nf --setup..` without -r

this should execute the master branch which is v1.1.0

I try to find the problem and report it when I found the issue

**Comment by lingyi-owl** [comment]
so I shouldn't use Conda, just download the v1.1.0 file, unzip it and do git pull?

**Comment by lingyi-owl** [comment]
did it in the What_the_Phage repo cloned from the website, activated the Conda environment, and still got the same error

$~/What_the_Phage:nextflow run replikation/What_the_Phage -r v1.1.0 --setup -profile local,singularity
N E X T F L O W  ~  version 20.07.1
Cannot find revision `v1.1.0` -- Make sure that it exists in the remote repository `https://github.com/replikation/What_the_Phage`

**Comment by mult1fractal** [comment]
what worked for me:
`nextflow drop replikation/What_the_Phage`
in the WtP repo
`nextflow run replikation/What_the_Phage --fasta ./test-data/stub_genome.fasta -stub -profile stub --cores 2 --max_cores 2 --dv --mp --pp --sm --vb -latest`

-latest executes the master branch =v1.1.0
@lingyi-owl could you please test this in your conda environment?
This is also just a quick fix
I don't know yet why nextflow does not see -r v1.1.0

**Comment by lingyi-owl** [comment]
Quickly tried you code and got this error:

```
$~/What_the_Phage:nextflow run replikation/What_the_Phage --fasta ./test-data/stub_genome.fasta --cores 2 --max_cores 2 --dv --mp --pp --sm --vb -latest
N E X T F L O W  ~  version 20.07.1
Pulling replikation/What_the_Phage ...
downloaded from https://github.com/replikation/What_the_Phage.git
Launching `replikation/What_the_Phage` [determined_payne] - revision: 1e53b61915 [master]
WtP requires at least Nextflow version 21.04.0 -- You are using version 20.07.1
```

I will update the nextflow version in Conda environment

**Comment by mult1fractal** [comment]
Im running nextflow version 21.10.6

**Comment by lingyi-owl** [comment]
it seemed running well this time but it didn't show the version of the wtp only showed a revision id:

`Launching `replikation/What_the_Phage` [condescending_mandelbrot] - revision: 1e53b61915 [master]`

**Comment by mult1fractal** [comment]
if you saw the folling in the nextflow execution
`[ed/068a84] process > markdown_report_wf:upsetr_report (1)                   [100%] 1 of 1 ✔
[5c/70b911] process > markdown_report_wf:heatmap_table_report (1)            [100%] 1 of 1 ✔
[bb/043327] process > markdown_report_wf:checkV_report (1)                   [100%] 1 of 1 ✔
[-        ] process > markdown_report_wf:annotation_table_report             -
[14/9c2019] process > markdown_report_wf:taxonomic_classification_report (1) [100%] 1 of 1 ✔
[bb/f34f51] process > markdown_report_wf:sample_report (1)                   [100%] 1 of 1 ✔
[6d/326df2] process > markdown_report_wf:summary (1)                         [100%] 1 of 1 ✔`

you know you run the most recent version
so if analyzing real data use `-latest` for now

as soon as I know whats the issue with -r v1.1.0 I will report back here

**Comment by lingyi-owl** [comment]
thanks!

**Comment by dangchenyuan** [comment]
@lingyi-owl 
I still have not resolved the error following these above steps. Could you help me solve this problem?

**Comment by dangchenyuan** [comment]
What means of the parameter of "-profile stub"? I only found "local, slurm, lsf, ebi, local, etc.".


> what worked for me: `nextflow drop replikation/What_the_Phage` in the WtP repo `nextflow run replikation/What_the_Phage --fasta ./test-data/stub_genome.fasta -stub -profile stub --cores 2 --max_cores 2 --dv --mp --pp --sm --vb -latest`
> 
> -latest executes the master branch =v1.1.0 @lingyi-owl could you please test this in your conda environment? This is also just a quick fix I don't know yet why nextflow does not see -r v1.1.0

**Comment by mult1fractal** [comment]
stub generates dummy files for each process 
imagine a "dry-run" of wtp without real data or sequences
its easier for development and checking eg. if I have the correct channels and processes linked

I think you shpould completely remove wtp from your system an clone the most recent git repo
`git clone https://github.com/replikation/What_the_Phage.git`

**Comment by caris1988** [comment]
I I had the same problem. Just type "v.1.1.0" instead of "v1.1.0".

**Comment by dangchenyuan** [comment]
> I I had the same problem. Just type "v.1.1.0" instead of "v1.1.0".

so it work well with "v.1.1.0" ?

**Comment by mult1fractal** [comment]
I just created a new release where `-r v1.1.0`  is the correct release
as it is stated in the manual and the readme in this repo

so please do `nextflow pull replikation/What_the_Phage`
