### ISSUE TITLE
Tasks are ABORTED&FAILED ，Running time too long

### ISSUE THREAD

**Issue by bio-shun** [replikation/What_the_Phage#163]
Hello, author!
My ubantu system uses docker to install Wtp v1 1.0. After installing the database (nextflow run replication / what_the_ph - R V1.1.0 -- setup - profile local, docker), Test the workflow (nextflow run replication / what_the_ph - R V1.1.0 -- cores 8 - profile smalltest, local, docker) and 'execution_report_test.html' displays successful in the file. The above can be considered that wtpv1.1.0 has been successfully installed and tested , when I use Wtp v1.1.0 identify  own "select.fasta"（57Mb） file ,there are errors in deepvirfinder and virnet recognition , so that the program has not finished running for 1D and 22h (see execution_report_select.html and execution_timeline_select.html for operation information). How to solve this problem?
Thank you very much！
[runinfo(test&select).zip](https://github.com/replikation/What_the_Phage/files/8649421/runinfo.test.select.zip)

**Comment by replikation** [comment]
one quick solution would be to deactivate them ( see --help). difficult to say why they are taking so long without knowing your system and the input file

**Comment by mult1fractal** [comment]
could you reduce the the select.fasta to one sequence and rerun? (without deepvirfinder and virnet)
