### ISSUE TITLE
Could not run wtp with 'nohup'

### ISSUE THREAD

**Issue by quliping** [replikation/What_the_Phage#168]
Wtp is a wonderful software and it help me a lot. However, I had some problems
I want to run wtp with the 'nohup' command. Wtp exit immediately after I ran my script:
![微信截图_20220713120119](https://user-images.githubusercontent.com/39583607/178648118-8c2bc7fb-5184-4707-bc3e-fc67a71110bc.png)

Here are my  command lines in the sh file:
conda activate wtp
nextflow run /public/apps/What_the_Phage-1.1.0/phage.nf --cores 32 -profile local,singularity --databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir ./wtpwork --fasta 03_connected_assembly/assembly-all.fasta --output A_vrius_wtp
conda deactivate

Here is my wtp log:
[wtp.log](https://github.com/replikation/What_the_Phage/files/9098810/wtp.log)

However, I could finish the calculate if I run the same commands directly in the terminal.

Looking forward to your reply.

**Comment by mult1fractal** [comment]
hey thank you for the nice feedback :)

Unfortunately this is the first time that I see this command... so I did not tested this

If I understand correctly it continues the program/command even if the terminal is closed.
In this case I use [screen](https://linuxize.com/post/how-to-use-linux-screen/)
I use screen eg. if I work from home. I start the process or workflow regular in the screen (wich is basically your standard terminal) and then terminate the screen-terminal. The workflow/process still continues.

you can also re-attach your screen-terminal to see what happens 

I hope it helps with your issue

**Comment by quliping** [comment]
> hey thank you for the nice feedback :)
> 
> Unfortunately this is the first time that I see this command... so I did not tested this
> 
> If I understand correctly it continues the program/command even if the terminal is closed. In this case I use [screen](https://linuxize.com/post/how-to-use-linux-screen/) I use screen eg. if I work from home. I start the process or workflow regular in the screen (wich is basically your standard terminal) and then terminate the screen-terminal. The workflow/process still continues.
> 
> you can also re-attach your screen-terminal to see what happens
> 
> I hope it helps with your issue

Thanks for your reply. Your understanding is completely right and your advice is working. Thank you so much!!!! 
![0B7BFC89](https://user-images.githubusercontent.com/39583607/178682749-32720716-06dc-4be2-a76b-dc0c77df1334.png)
