### ISSUE TITLE
Some tasks failed when using v1.2.0 of Wtp

### ISSUE THREAD

**Issue by quliping** [replikation/What_the_Phage#173]
I'm so happy that the question which I mentioned before about [virsorter2](https://github.com/replikation/What_the_Phage/issues/169#issuecomment-1214987138) was solved. By the way, previous quention about [phigaro](https://github.com/replikation/What_the_Phage/issues/169#issuecomment-1205092921) was also resovled by running `singularity run /public/cachedir/multifractal-phigaro-0.5.2.img` then `phigaro-setup --no-updatedb`.  However, I got some other problems. 

Here is my command: 
```
conda activate wtp
cat list-all.txt|while read line
do
if [[ ! -d "A_vrius_wtp/${line}" ]]; then mkdir "A_vrius_wtp/${line}"; fi
if [[ ! -d "wtpwork_temp/${line}_workdir" ]]; then mkdir "wtpwork_temp/${line}_workdir"; fi
nextflow run /public/apps/What_the_Phage-v1.2.0/phage.nf --filter 1000 --cores 72 -profile local,singularity \
--databases /public/data/database/wtp_database --cachedir /public/cachedir --workdir wtpwork_temp/${line}_workdir \
--fasta 03_connected_assembly/${line}.fasta --output A_vrius_wtp/${line} --all_tools
done
conda deactivate
```

Here is the report: [execution.zip](https://github.com/replikation/What_the_Phage/files/9680554/execution.zip)

**These tasks failed using v1.2.0 but successed using v1.1.0:** 
1. deepvirfinder_wf:deepvirfinder
[36.zip](https://github.com/replikation/What_the_Phage/files/9680550/36.zip)
![image](https://user-images.githubusercontent.com/39583607/193187023-368c41bd-8716-496a-bf65-ab69667092ae.png)

2. virnet_wf:virnet
[b7.zip](https://github.com/replikation/What_the_Phage/files/9680552/b7.zip)
![image](https://user-images.githubusercontent.com/39583607/193187078-11269cac-ff62-422c-bc6f-6f4014c35ec3.png)

3. markdown_report_wf:summary
[35.zip](https://github.com/replikation/What_the_Phage/files/9680558/35.zip)
![image](https://user-images.githubusercontent.com/39583607/193187118-5e96d3c4-d385-4479-a5d4-809f86e315d1.png)

4. phage_annotation_wf:chromomap
[b3.zip](https://github.com/replikation/What_the_Phage/files/9680561/b3.zip)
![image](https://user-images.githubusercontent.com/39583607/193187162-bb2f5397-07c3-4519-9017-448303f56372.png)

Problem 4 also occurred using test data: 
```
nextflow run /public/apps/What_the_Phage-v1.2.0/phage.nf --cores 16 -profile smalltest,local,singularity \
--cachedir /public/cachedir --databases /public/data/database/wtp_database
```
[execution_test.zip](https://github.com/replikation/What_the_Phage/files/9680576/execution_test.zip)
[b6.zip](https://github.com/replikation/What_the_Phage/files/9680577/b6.zip)
![image](https://user-images.githubusercontent.com/39583607/193186928-98e605aa-e8da-4f6c-850f-5ff43c188252.png)

Problem 1, 2, and 3 not occurred when using test data.

**Comment by mult1fractal** [comment]
Hey quliping

1 & 2
the difference from v1.1.0  to v1.2.0 is that I removed not benchmarked tools them from the default execution.
So I did not touch any tool processes. It also seems more tensorflow related?  But unfortunately I have no experience with tensorflow.

3. 
Yes this is a real problem... see here #169 
again I need the files to solve this

4.
I will run your command and check what happened

**Comment by quliping** [comment]
Thanks for your reply. You mean the files from work dir, right? I put associate files just above the picture from each problem. For problem-3, the zip file was named '35.zip'. 
![image](https://user-images.githubusercontent.com/39583607/193235780-de7b6286-717a-41e8-8013-e12842aa552d.png)
You can also use this link to download: https://github.com/replikation/What_the_Phage/files/9680558/35.zip

**Comment by mult1fractal** [comment]
I used the following command: 
```nextflow run phage.nf -profile local,docker,smalltest -work-dir /media/6tb_1/work/ --cores 20```

and the workflow finished succesfully.
could you delete and reload the singularity image? (nanozoo/r_fungi:0.1--097b1bb)
idk why the docker?singularity image is not working now... it is locked to a specific version (I also didnt touched it in the new release)

I will also clean my docker cache and rerun the command

**Comment by mult1fractal** [comment]
so I removed all docker containers installd on my machine and run the command again
```nextflow run phage.nf -profile local,docker,smalltest -work-dir /media/6tb_1/work/ --cores 20```

the workflow finished successfully and I can't reproduce this error.
Also your files look fine (b6)
