### ISSUE TITLE
Deepvirfinder error

### ISSUE THREAD

**Issue by deminatanja** [replikation/What_the_Phage#176]
Hi,

I have comes across the following error with Deepvirfinder when running WtP:
...
FileExistsError: [Errno 17] File exists: '/users/MY_USER_NAME/.theano/compiledir_Linux-4.18-el8_6.x86_64-x86_64-with-debian-10.0--3.6.9-64/lock_dir'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/DeepVirFinder/dvf.py", line 184, in <module>
    head, score, pvalue = zip(*pool.map(pred, range(0, len(code))))
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileExistsError: [Errno The following error happened while compiling the node] Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)](TensorConsta
nt{(1, 1, 1) of 0.5}, Reshape{3}.0, InplaceDimShuffle{x,x,0}.0): '\n' -> 'File exists'

I have already tried to remove .theano folder completely and tried to run WtP again, but still got the same error message.

What could I do to resolve this?

Best,
Tatiana

**Comment by mult1fractal** [comment]
Hi,
I think this is more related to Deepvirfinder then WtP

I think we had an `.theano` issue before #31 

Could you run WtP with a smaller fasta input file: ~50Mb
