### ISSUE TITLE
Pharokka for phage annotation

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#177]
Paper:
https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btac776/6858464?login=false

Code:
https://github.com/gbouras13/pharokka

I build a container already:
`docker run --rm nanozoo/pharokka:1.1.0--46a5c6b pharokka.py --help`

And I also installed the necessary databases in the container (they are small). So it should be possible to run the tool w/o downloading the databases and just specifying:

```bash
pharokka.py -i assembly.fasta -o output -t 4 -d pharokka_database_v1.0.0/
```

*Attention*: there seems to be a parameter for multiFASTA (metagenomic) input activated via `-m`

**Comment by mult1fractal** [comment]
Nice 👍🏼
Thank you Martin!

**Comment by mult1fractal** [comment]
- use pharokka as default annotation
- get results from checkv
- create map from contigs with completeness above 75%
