### ISSUE TITLE
Add optional parameters for workdir, params.cloudDatabase, and cacheDir

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#18]
Currently, the LSF configuration looks like this:

````
 lsf {
        params.cloudProcess = true
        params.cloudDatabase = '/homes/mhoelzer/data/nextflow-databases/'
        workDir = "/hps/nobackup2/production/metagenomics/mhoelzer/nextflow-work-$USER"

        process.executor = 'lsf'
        singularity {
            enabled = true
            autoMounts = true
            cacheDir = "/hps/nobackup2/singularity/mhoelzer"
        }
        params.cpus = params.cores

        process {
            cache = "lenient"
            withLabel: virsorter { cpus = 8; memory = '8 GB'; container = 'multifractal/virsorter:latest' }
} }
````

So fixed to my environment at the EBI LSF. Do you agree that it would be good to have input parameters for 

* cloudDatabase //here are the databases stored, default could be ./nextflow-autodownload-databases
* workDir //here are the work files written, this can be a lot of stuff and I have to define a specific place for this on the cluster here, default could be /tmp/nextflow-phages-$USER
* cacheDir //this I need to tell Singularity where the images are

If you agree, I would implement this.

**Comment by replikation** [comment]
yeah makes sense. maybe we can adjust the whole config to the nanozoo style of config abstraction? would make the whole config structure clean? so dockers are separated configs/

**Comment by replikation** [comment]
please also add all issues to the phage project page :)

**Comment by hoelzer** [comment]
yeah, sounds reasonable. I already implemented the additional parameters in an extra branch 'lsf'. 

I can also do the nz style configuration now and then merge. 

@project page... ah sorry, forgot. jip.

**Comment by replikation** [comment]
perfect would be great if you add the nz style

**Comment by hoelzer** [comment]
Done, its working for me at the EBI cluster with additional input parameters to adjust paths that are needed to be defined user specific on the cluster structure. 

@replikation @Stormrider935 can you please do a 

````
git pull
git checkout lsf
nextflow run phage.nf --fasta test-data/POI_draft.fa
````

and confirm that also the local version is still working? I currently have some weird 'no space left on device' issues on my mac here (although 200GB are free). 

If this works for you, I would merge the 'lsf' branch into 'master' and close this

**Comment by replikation** [comment]
* lsf works fine locally on the hospital workstation can be merged :+1:

**Comment by hoelzer** [comment]
great, will do the merge and close this now.
