### ISSUE TITLE
computational cost

### ISSUE THREAD

**Issue by 444thLiao** [replikation/What_the_Phage#181]
I noticed that there are multiple software that requires database. 

For example,

```process vibrant {
    label 'vibrant'
    errorStrategy 'ignore'
    input:
        tuple val(name), path(fasta) 
        path(db)
    output:
        tuple val(name), path("vibrant_*.tsv")
        // output collection stream
        tuple val(name), path("vibrant_*.tsv"), path("VIBRANT_results_*.tar.gz")
    script:
        """
      
        tar xzf ${db}
```

However, each run might need to unzip the database file again, which raise the computation cost.
Here, I strongly advise that it could be changed via **soft link** or other ways to save these times.

best wishes

**Comment by replikation** [comment]
only if you ignore data transfer costs and storage costs of these databases
