### ISSUE TITLE
running WtP without containers, using native installation of required tools

### ISSUE THREAD

**Issue by boegel** [replikation/What_the_Phage#186]
Is there a way to run WtP without using containers?

I understand that this implies that the required tools are available through some other mechanism (and that this can be painful)...

**Comment by replikation** [comment]
As there are way too many tools and dependencies involved no. For some tools we even need to write some "wrappes" so we can run them in a workflow.  The simplest solution would be the conda to singularity installation as outlined in the documents. also, as far as I know, it's not even possible to install securely all the tools due to various phyton versions and deps complications alone.

**Comment by boegel** [comment]
The reason I'm interested in doing a native installation is that using pre-built binaries (what containers and conda installations essentially are) could run significantly slower than from-source installations (which can be compiled with compiler options that produce optimized binaries for the specific hardware (CPU) on which they will be run).

Can you provide some pointers on where these wrappers that you mention are defined?

Do you have a particular example of two tools that require a different version of a particular dependency (like Python) that make it impossible to install them together in the same "environment"?

**Comment by replikation** [comment]
I see your point, but Dependency isolation and thus stability and reproducibility were way more important for us. 

A command wrapper example:
https://github.com/replikation/What_the_Phage/blob/master/bin/virfinder_execute.R

i mean if you want to "remove" containers and use native installs WtP will choose the native installed options automatically (aka searches in PATH for them) if you remove the "container = **" parts from here: https://github.com/replikation/What_the_Phage/blob/master/configs/container.config. 
This file contains all 26 different "install environments" - you could also replace the container via "conda" if you want. See https://www.nextflow.io/docs/latest/conda.html for some examples.

Installation commands for each tool can be "extracted" from the Dockerfiles that are located here: https://github.com/replikation/What_the_Phage/tree/master/phage-tool-Dockerfiles
if no Dockerfile is available than that means a normal conda install was all that's needed.



good luck
