### ISSUE TITLE
Testrun failed

### ISSUE THREAD

**Issue by xykb86** [replikation/What_the_Phage#190]
Hi developer,
I followed the quick installation instructions, and tried the testrun with the command: nextflow run phage.nf -profile smalltest,local,docker --work-dir work --cores 16

But the following message showed up:
N E X T F L O W  ~  version 23.04.3
Cannot find script file: phage.nf

How should I fix it?

**Comment by mult1fractal** [comment]
Hey

Did you execute the code in the What_the_Phage
Repository you cloned from GitHub?

If not you can also use the absolute path:
```
/Your/path/to/what_the_phage/phage.nf
```
