### ISSUE TITLE
Metaphinder Filter is not correctly working

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#23]
I think I found out why Metaphinder has such good results in your test data sets ;) 

The filtering simply selects all contigs. 

Your command in ``modules/filter_metaphinder.nf``:

````
sort  -g  -k4,4 SRR8811960_1.unclassified.txt | awk '$2>=phage' | awk '{ print $1 }' | tail -n+2
````

needs to be changed to 

````
sort  -g  -k4,4 SRR8811960_1.unclassified.txt | awk '$2>="phage"' | awk '{ print $1 }' | tail -n+2
````

or why not looking for 

````
awk '$2=="phage"'
````

?

I found this because of my Nanopore test run where VirSorter found 220 phages and Metaphinder reported 365,686 -- basically all of my input reads. By changing the above command I get 63,794 hits, still a lot but now only those labeled as phage. 

@Stormrider935 please confirm that I interpreted the output file of Metaphinder correctly and if so, fix the filter step.

**Comment by replikation** [comment]
is this fix of yours working? if so you can push it to master.
thx for the report

**Comment by hoelzer** [comment]
yeah, I also made the awk a little bit simpler:

````
sort -g -k4,4 !{results} | awk '{if(\$2=="phage"){print \$1}}' | tail -n+2 > metaphinder.txt
````

it is now. seems to work for me. pushed and closed

**Comment by replikation** [comment]
thank you very much
