### ISSUE TITLE
Some evaluation testing

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#27]
As I have to prepare some virus test data sets anyway I just run 4 assemblies through WtP. Honestly, I do not exactly know what to expect as an outcome from the files (I have to clarify with some guy that was working on a virus pipeline here before and used them). 

 ### The assemblies are:

* High_confidence_putative_viral_contigs.fna
* Low_confidence_putative_viral_contigs.fna
* tara_virus.fa
* putative_prophages.fna

Pipeline finished successfully (yeah, on the LSF system in 28m). 

However, I am concerned with the output, in particular not any hit with VirFinder. How do you filter the VirFinder output at the moment? And can you also please clarify again how the VirSorter output is filtered currently? 
(and of course, some heat map plot tuning is needed, but this might be anyway resolved by including UpSetR and might not be that important for now. 

### Results
[High_confidence_putative_viral_contigs.pdf](https://github.com/replikation/What_the_Phage/files/3846725/High_confidence_putative_viral_contigs.pdf)
[Low_confidence_putative_viral_contigs.pdf](https://github.com/replikation/What_the_Phage/files/3846728/Low_confidence_putative_viral_contigs.pdf)
[putative_prophages.pdf](https://github.com/replikation/What_the_Phage/files/3846729/putative_prophages.pdf)
[tara_virus.pdf](https://github.com/replikation/What_the_Phage/files/3846730/tara_virus.pdf)

**Comment by replikation** [comment]
even though the heatmap is quite "full/unreadable" I like the overview already :)
and yeah it run through. getting more stable now!

somehow virfinder looks broken, but @Stormrider935 is checking out all the values over the next days.

**Comment by replikation** [comment]
thanks for the test runs 👍

**Comment by hoelzer** [comment]
> thanks for the test runs 👍

Thanks for the nice pipeline ;) And yes, I also like the output! Already quite impressive how many contigs the other tools detect in comparison to VirSorter. However, still questionable how many of these are FP ;)

**Comment by replikation** [comment]
in the end every tool claimed to be better than the other... :D

**Comment by Stormrider935** [comment]
I will check all the filterscripts and outputs on saturday
👌🏻

**Comment by Stormrider935** [comment]
>somehow virfinder looks broken, but @Stormrider935 is checking out all the values over the next days.

- [x] Virfinder has been fixed
