### ISSUE TITLE
`fasta_validation_wf` declares 0 input channels but 1 were specified 

### ISSUE THREAD

**Issue by Stormrider935** [replikation/What_the_Phage#28]
* I wanted to run the workflow  `nextflow run replikation/What_the_Phage` and `nextflow run phage.nf` so i could try to implement samtools and grab positive ctgs but instead i got this error:
>Profile: standard
 
>Current User: mike
Nextflow-version: 19.07.0
Starting time: 27-07-2019 13:22 UTC
Workdir location:
  /tmp/nextflow-phages-mike
 
>CPUs to use: 8
Output dir name: results
 
>Workflow `fasta_validation_wf` declares 0 input channels but 1 were specified

> -- Check script 'What_the_Phage/phage.nf' at line: 179 or see '.nextflow.log' file for more details

##### commands
* `nextflow run What_the_Phage/phage.nf --fasta What_the_Phage/test-data/T7_draft.fa `
* `nextflow run replikation/What_the_Phage --fasta What_the_Phage/test-data/T7_draft.fa `

**Comment by replikation** [comment]
@Stormrider935 cant reproduce

**Comment by replikation** [comment]
[d0/e2c14d] process > fasta_validation_wf:input_suffix_check (1) [100%] 1 of 1 ✔

**Comment by Stormrider935** [comment]
mike@mike-Yoga-13:~/bioinformatics/What_the_Phage$ `nextflow run replikation/What_the_Phage --fasta 'test-data/T7_draft.fa' --cores 1`


>N E X T F L O W  ~  version 19.07.0
Launching `replikation/What_the_Phage` [berserk_blackwell] - revision: c9e6f906df [master]
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
>_____ _____ ____ ____ ___ ___ __ __ _ _ 
>  __      _______________________ 
> /  \    /  \__    ___/\______   \
> \   \/\/   / |    |    |     ___/
>  \        /  |    |    |    |    
>   \__/\  /   |____|    |____|    
>        \/                        
>_____ _____ ____ ____ ___ ___ __ __ _ _ 
> 
>Profile: standard
> 
>Current User: mike
>Nextflow-version: 19.07.0
>Starting time: 27-07-2019 13:22 UTC
>Workdir location:
>  /tmp/nextflow-phages-mike
 
>CPUs to use: 1
Output dir name: results
 
>Workflow `fasta_validation_wf` declares 0 input channels but 1 were specified

> -- Check script '/home/mike/.nextflow/assets/replikation/What_the_Phage/phage.nf' at line: 179 or >see '.nextflow.log' file for more details

* after this I used `nextflow pull replikation/What_the_Phage` startetd the wf again 
mike@mike-Yoga-13:~/bioinformatics/What_the_Phage$ `nextflow run replikation/What_the_Phage --fasta 'test-data/T7_draft.fa' --cores 1` and got the same error

**Comment by replikation** [comment]
master branch?

**Comment by replikation** [comment]
N E X T F L O W ~ version 19.07.0

**Comment by replikation** [comment]
please upgrade to 19.10 as specified in the readme
