### ISSUE TITLE
Get phage positive reads

### ISSUE THREAD

**Issue by replikation** [replikation/What_the_Phage#34]
# enhancement
* WtP should extract the "phage" positive hits from the fastq files and give it to the user as a  result output
* similar to samtools and contigs
* this would make downstream analysis much more useful after the classifications

**Comment by Stormrider935** [comment]
# additional enhancement
* i think the option to run WTP with only one phage tool or two or three would be a nice addition
* eg.:  `nextflow run replikation/What_the_Phage --fasta /foo/bar --tools_to_include virfinder virsorter`

* this would give the user more freedom if they just want to check one tool

**Comment by hoelzer** [comment]
@Stormrider935 actually I agree, that is a good idea. The single tools are already a pain-in-the-ass to execute them and WtP would wrap also the single execution. Such functionality would be quite neat. And should be relatively simple to integrate, right?

**Comment by Stormrider935** [comment]
* this should be also easier for us eg. testing of large fasta-files ... if one tool is messing around we can check if it is just the one tool or if the others are working properly

**Comment by replikation** [comment]
@Stormrider935 the other way around is what we should go for: tools to exclude

**Comment by replikation** [comment]
reasigned to me, will implemented this

**Comment by replikation** [comment]
reassigned to me, will implement this
