### ISSUE TITLE
Metaphinder validation testing

### ISSUE THREAD

**Issue by Stormrider935** [replikation/What_the_Phage#39]
* I put together 2 data-sets  for validation testing :

1.  10 files (pos_phage_x.fa)

2.  10 files (neg_phage_x.fa) 

structure of the files for validation testing:
`>pos.phage.0
GCTACCTGGTGCACCGTGCCGCCTTGCCAGCCCAATGAGTGCATGAGATGTAAAGGAGTATTTGTCATGGTATCGCCCTTTCTTTGATGTGCGCCCTGGTTG`

structure of the `What_the_Phage/test-data/*.fa`
`>ctg1 len=150545
GCTACCTGGTGCACCGTGCCGCCTTGCCAGCCCAATGAGTGCATGAGATGTAAAGGAGTATTTGTCATGGTATCGCCCTTTCTTTGATGTGCGCCCTGGTTG`

* the Idea was an easy readout- system for the phagedistribution.pdf output from WTP

* I testet WTP on the data-sets:
`nextflow run replikation/What_The_Phage --fasta pos_phage_1.fa`

```bash
>Error executing process > 'metaphinder_wf:metaphinder (1)'

>Caused by:
  Process `metaphinder_wf:metaphinder (1)` terminated with an error >exit status (1)

>Command executed:

  >rnd=0.18523026702354528
  mkdir pos_phage_1
  MetaPhinder.py -i pos_phage_1.fa -o pos_phage_1 -d /MetaPhinder/>database/ALL_140821_hr
  mv pos_phage_1/output.txt pos_phage_1_${rnd//0.}.list

>Command exit status:
  1

>Command output:
  parsing commandline options...

>Command error:
  Traceback (most recent call last):
    File "/MetaPhinder/MetaPhinder.py", line 154, in <module>
      contigID,size = get_contig_size(contigfile)
    File "/MetaPhinder/MetaPhinder.py", line 29, in get_contig_size
      if l[0] == ">":
  IndexError: string index out of range
```

* I tried to perform the task just in the docker
`docker run --rm -it  -v $PWD:/home/mike/bioinformatics/Phage_fasta_files/pos_neg.phage_data/allinone/ multifractal/metaphinder:0.1 /bin/bash`

* and inside:
`MetaPhinder.py -i pos_phage_1.fa -o output.txt -d /MetaPhinder/database/ALL_140821_hr`

>parsing commandline options...
>Traceback (most recent call last):
  File "/MetaPhinder/MetaPhinder.py", line 154, in <module>
    contigID,size = get_contig_size(contigfile)
  File "/MetaPhinder/MetaPhinder.py", line 29, in get_contig_size
    if l[0] == ">":
>IndexError: string index out of range

* as control I downloaded the [T7 bacteriophage genome fastafile](https://www.ncbi.nlm.nih.gov/nuccore/V01146) and got the same problem in nextflow and docker

* as additional control I tried the commands above with our current `What_the_Phage/test-data/*.fa` test data: no problems

* The [github](https://github.com/vanessajurtz/MetaPhinder) page says this:
> MetaPhinder classifies metagenomic contigs as of phage origin or not based on a
comparison to a phage database.
The script relies on BLAST which must be installed on you machine prior to running
MetaPhinder.
The input to MetaPhinder is a FASTA file of metagenomic contigs.

* I will try to find contig-databases and put togehter a new set of phage pos. and neg. data that lookls like our current `What_the_Phage/test-data/*.fa` test data

* We should mention in the readme that you can't use some random fasta-files as input otherwise metaphinder will beef around

**Comment by replikation** [comment]
* can you remove the dots and just name the contig: > positive phage 0
* also put comman outputs into a code box (i edit it up there to show what i mean)

**Comment by Stormrider935** [comment]
* I changed the contig  to:  > positive phage 0
* did the same testing with the new fasta header as mentioned above (Nextflow and Docker) and got exactly the same Error messages

**Comment by replikation** [comment]
* what happens when you replace the > positive phage fasta headers with "working headers" from another file ?
* if it still got the error we know its not the fasta header its something with the sequence

* i mean the error is somehow related to "get contig size"
```bash
File "/MetaPhinder/MetaPhinder.py", line 29, in get_contig_size
if l[0] == ">":
```
* so are there spaces or other nucleaotides in place of ATGC?
* try and find out what the difference between the working and not working .fa is

**Comment by Stormrider935** [comment]
#### Solution
* Downloaded single fatsa Sequences from NCBI have a wordwrap after the last Base
* after deleting this wordwrap at the end metaphinder was running smooth

**Comment by replikation** [comment]
yep sounds good. i think you could add this as a pipe to one of the other commands that modifiy the fasta headers and such

**Comment by Stormrider935** [comment]
testing with the code `grep -v -e '^$' file.fa` integrated in the input-check module
* I tested our `What_the_Phage/test-data/*.fa` files: works
* I tested a small fasta file freshly downloaded from ncbi: works
* I tested my pos_phage/neg_phage : doesn't work 
I get the same error msg as in #20 :

```shell
Caused by:
  Process `marvel_wf:marvel (3)` terminated with an error exit status (1)

Command executed:

  rnd=0.53550569370831
        mkdir fasta_dir_neg_phage_9 
        cp neg_phage_9.1.fa fasta_dir_neg_phage_9/
        # Marvel
        marvel_bins.py -i fasta_dir_neg_phage_9 -t 8 > results.txt
        # getting contig names
        filenames=$(grep  "neg_phage_9\." results.txt | cut -f2 -d " ")
        while IFS= read -r samplename ; do
         head -1 fasta_dir_neg_phage_9/${samplename}.fa >> neg_phage_9_${rnd//0.}.list
        done < <(printf '%s
  ' "${filenames}")

Command exit status:
  1

Command output:
  (empty)

Command error:
  /usr/local/lib/python3.6/dist-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
    UserWarning)
  /usr/local/lib/python3.6/dist-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
    UserWarning)
  head: cannot open 'fasta_dir_neg_phage_9/.fa' for reading: No such file or directory

```

**Comment by replikation** [comment]
* @Stormrider935 can you please attach the problematic file
* you are also sure that there are no additional "symbol" issues?

**Comment by replikation** [comment]
* the issue is the "negative" file
* the absence of any phages
