### ISSUE TITLE
upsetr enhancements 

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#42]
The current output of the upsetr module looks like this:

<img width="767" alt="Screenshot 2019-12-13 14 08 04" src="https://user-images.githubusercontent.com/14393703/70805914-009e9b00-1db2-11ea-9a1b-847c00b06319.png">

__todo__:

* increase plot margin to not cut off the numbers 
* plot also as high-quality PNG/PDF next to the SVG
* potentially add other [fancy upsetr features with metadata](https://cran.r-project.org/web/packages/UpSetR/vignettes/set.metadata.plots.html)

**Comment by replikation** [comment]
@hoelzer can you give me the code snipped to remove the numbers from the blue bars?

**Comment by hoelzer** [comment]
@replikation I think you simply have to change 

```
set_size.show = TRUE
```

to

```
set_size.show = FALSE
```

**Comment by replikation** [comment]
* thanks was working fine
