### ISSUE TITLE
Splitting large input files into single FASTAs (Marvel, ...) produces many files

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#46]
I think the current procedure of splitting a multi-FASTA-file into single FASTA files only containing one contig can cause trouble for large input files (like done for Marvel). 

```
(base) [mhoelzer@noah-login-01 ~]$ ls data/nextflow-work-mhoelzer/b1/139ca96b107d491ef6fb4d534361f9/H52_0_1_2_contigs/*.fa | wc -l
-bash: /usr/bin/ls: Argument list too long
```

Let's say you have an assembly with 500k contigs then you produce a single folder with 500k files. 

I recommend, if possible, working with subfolders and only store 1k or so files into one folder.

**Comment by replikation** [comment]
closing this, we will tackle this via #47
