### ISSUE TITLE
-resume is not working anymore? 

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#48]
Is it possible that ``-resume`` is not working anymore? Maybe because ot the rnd IDs you are producing? 

```
nextflow run phage.nf --fasta test-data/OX2_draft.fa --cores 4 --resume
```

does all the steps again for me (except stored data bases)

**Comment by hoelzer** [comment]
Ok wait, it might have been some issue with my file system

**Comment by hoelzer** [comment]
Ok srry, everything is cached except 

```
[d2/6104bb] process > marvel_wf:marvel (1)                    [  0%] 0 of 1
[-        ] process > marvel_wf:filter_marvel                 -
```

I think because you split the FASTA?

**Comment by replikation** [comment]
yeah might be true. random is resuming or? didnt had issues there. -resume is not perfect in some cases :/

**Comment by replikation** [comment]
closing as this is nothing i can change :)
