### ISSUE TITLE
Problems with dockers

### ISSUE THREAD

**Issue by Stormrider935** [replikation/What_the_Phage#5]
# General thread to talk and solve Dockerfile issues

**Comment by Stormrider935** [comment]
* i have the same problem if i attach another 1 to the code like this `printf '1\n1\n1\nn'`
* it still stops here ..
>Please select appropriate Prodigal location
[1] /opt/conda/bin/prodigal
[2] Add another path manually
Choose your option (Enter for /opt/conda/bin/prodigal): Please select appropriate HMMER location
[1] /opt/conda/bin/hmmsearch
[2] Add another path manually
Choose your option (Enter for /opt/conda/bin/hmmsearch):

**Comment by Stormrider935** [comment]
* Problem solved.. maybe...
* I tried the following base image: `From continuumio/miniconda2` and not `miniconda 3`
* seems to work
* but it's python 2.7....

**Comment by replikation** [comment]
we cant go into the /phigaro workdir. we have a separate process dir in nextflow

**Comment by Stormrider935** [comment]
* phigaro takes only ctgs > 20000bp
* smaller ctgs will not be analyzed
* for module:
```
"""
printf 'Y' | phigaro -f test_data/Bacillus_anthracis_str_ames.fna -o test_data/Bacillus_anthracis_str_ames.phg -p --not-open
"""
* parse Y because phigaro asks if it should start w/o smaller ctgs

```
