### ISSUE TITLE
VirFinder run in parallel

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#52]
VirFinder is one of the slow tools for large input data. However, there is a parallel version that might be interesting to implement:

virfinder repo: 
> VirFinder can be run in parallel using multiple cores. See script here. Thanks for the contributions from R. Eric Collins.

https://github.com/rec3141/VirFinder/blob/master/linux/VirFinder/R/parVF.pred.R

**Comment by replikation** [comment]
* this R stuff .... iam closing this. if it gets a problem we do split fasta or so

**Comment by hoelzer** [comment]
yeah good idea... actually in all my last tests virfinder was at the end not the slowest tool. So honestly: who cares.
