### ISSUE TITLE
sourmash error for NCBI phage FASTA header

### ISSUE THREAD

**Issue by hoelzer** [replikation/What_the_Phage#53]
Input:
https://www.rna.uni-jena.de/supplements/wtp/zheng_2019.fasta

Error:
```
Caused by:
  Process `sourmash_wf:split_multi_fasta (2)` terminated with an error exit status (1)

Command executed:

  mkdir zheng_2019_contigs/
  
  while read line
    do
  if [[ ${line:0:1} == '>' ]]
  then
    outfile=${line#>}.fa
    echo ${line} > zheng_2019_contigs/${outfile}
  else
    echo ${line} >> zheng_2019_contigs/${outfile}
  fi
    done < zheng_2019.fa

Command exit status:
  1

Command output:
  (empty)
```

I think the problem is parsing such crazy NCBI FASTA header? 
```
  .command.sh: line 9: zheng_2019_contigs/gi|1003341871|gb|KU310943_1|__Pseudomonas__phage__YMC11/07/P54_PAE_BP___complete__genome.fa: No such file or directory
```

You might consider renaming all FASTA ids to something useful in the beginning off WtP and then re-renaming at the end.

**Comment by replikation** [comment]
@hoelzer
we remove problematic symbols here:
https://github.com/replikation/What_the_Phage/blob/master/modules/input_suffix_check.nf

the last lines are there to remove problematic symbols to just underscores.
you could add this and see if it works:
`````
sed 's#\\|#_#g' -i ${name}.fa
````
otherwise we could also implement another solution? like first rename all fasta and then rename it back.

**Comment by hoelzer** [comment]
@replikation thx, yes I already renamed my header too 

contig1
contig2
...

as a fast fix. 

Maybe you want to simply add replacement of ``|`` symbols in ``input_suffix_check.nf``? 

But yes, the most _save_ way in my eyes is to rename all fasta and then rename them back.

**Comment by replikation** [comment]
@Stormrider935 can you add this to your current branch?
