### ISSUE TITLE
deactivating all tools except one fails upsetr

### ISSUE THREAD

**Issue by replikation** [replikation/What_the_Phage#55]
* upsetR wont plot if it has only one input file
* reproduce via:
   * `./phage.nf -profile git_action`
* WtP ignores this error but still creates the heatmap (so no big issue)

* Error message:
````bash
Error in 1:ncol(data) : argument of length 0
Calls: upset -> FindStartEnd
````
* thats all the error messages here

**Comment by hoelzer** [comment]
What is the behavior we want to have here? An UpsetR plot with one file is anyway not that useful.

I can modify the R code to check if there is only one input file to do nothing. Or likely we can just use the nextflow ``when`` directive to check if there is only one file and if so do not execute the process?

**Comment by replikation** [comment]
* we could ignore it of course as it is pointless on upsetR
* the current status is that the process fails but WtP ignores it and finishes successfully either way
* for documentation's sake its an issue but we can close it
