### ISSUE TITLE
Lenght Cut-off for input sequences

### ISSUE THREAD

**Issue by mult1fractal** [replikation/What_the_Phage#59]
*  @hoelzer : For example the Tara ocean virome paper uses a combinations of virsorter/virfinder and a length cutoff of 1.5kb. Personal communicatiom with matt sullivan: He would not trust any classified contig below 5k ;) and the lenght Filter will reduce run time of All Tools and yield a better heatmap/upset fig that is more reliable. Atm pprmeta and virfinder Report insane high numbers because they als predict almost all super short contigs as phages

**Comment by replikation** [comment]
* in the nextflow config add a `params.filter = '1500'`  so its 1500 by default and user can use 
the `--filter` flag to increase or decrease this
* I suggest adding a separate process directly after the fasta input check process

**Comment by mult1fractal** [comment]
* default filter 1.5 kb
* experienced users : turn off filter ---but it will result in an increased number of short hits  and false positve

**Comment by replikation** [comment]
no dont use a "turn off" flag, just give the option to modify this, like suggested one comment above by me

**Comment by mult1fractal** [comment]
Reminder to myself:
* Testfile: T7_draft.fa
* command: 
```shell
nextflow run phage.nf --fasta test-data/T7_draft.fa --dv --ma --pp --sm --vb --vf --vn --vs --anno --filter 100000
```
* so the length filter is working fine: `--filter 100000` filters everything under 100000 bp.
* tools: eg metaphinder is detecting in T7 draft ctg1 a phage positive signal
* but in The final results all plots are empty... and the pos_phage_file generated from samtools is also empty
* i checked the processfolder for metaphinder: file T7_draft_6624aee964b16711757b4b877f6976.list shows a positive phage detection
* problem occurs somewhere in the filter

**Comment by mult1fractal** [comment]
* to check whats wrong I switched the branch to master to see if I have the same issue here...
* I ran 
```shell
nextflow run phage.nf --fasta test-data/T7_draft.fa --dv --ma --pp --sm --vb --vf --vn --vs --anno -profile local,docker
```
* in the process folder for metaphinder_filter all files look as they should look like
* but somehow the Phage distribudion.pdf  is empty.... It shows the contigs and tools but there were no blue sqares....

**Comment by mult1fractal** [comment]
Next Problem: 
i'm testing with the T7_draft.fa
with this command:
```shell
nextflow run phage.nf --fasta test-data/T7_draft.fa --dv --ma --pp --sm --vb --vn --vs --anno -profile local,docker --cores 4 --filter 2000
```
metaphinder hits ctg 1,3,2,4 as positive with colour in the phage distribution.pdf (rplot)

with this command:
```shell
nextflow run phage.nf --fasta test-data/T7_draft.fa --dv --ma --pp --sm --vb --vn --vs --anno -profile local,docker --cores 4 --filter 100000
```
vifinder hit ctg1 and marks it blue but metaphinder hit ctg1
* here the problem is located in the Metafinder filter modul:
* metaphinder detect ctg1 as phage: 7_draft_3fc4de88dffa6b4aed37ed2119dc8f.list , but can't apply the the filter code for the positive hits

**Comment by replikation** [comment]
implemented by @mult1fractal
