### ISSUE TITLE
.command.sh: No such file or directory

### ISSUE THREAD

**Issue by stefanches7** [replikation/What_the_Phage#64]
## Expected behaviour
Input (all_contigs.fa) is formatted accordingly for later processes
##  Observed behaviour

```
Error executing process > 'fasta_validation_wf:input_suffix_check (1)'

Caused by:
  Process `fasta_validation_wf:input_suffix_check (1)` terminated with an error exit status (1)

Command executed:

  case "all_contigs.fa" in
      *.gz) 
          zcat all_contigs.fa > all_contigs.fa
          ;;
      *.fna)
          cp all_contigs.fa all_contigs.fa
          ;;
      *.fasta)
          cp all_contigs.fa all_contigs.fa
          ;;
      *.fa)
          ;;
      *)
          echo "file format not supported...what the phage...(.fa .fasta .fna .gz is supported)"
          exit 1
  esac
  
  # tr whitespace at the end of lines
  sed 's/[[:blank:]]*$//' -i all_contigs.fa
  # remove ' and "
  tr -d "'"  < all_contigs.fa | tr -d '"' | tr -d "[]" > tmp.file && mv tmp.file all_contigs.fa
  # replace ( ) | . , / and whitespace with _
  sed 's#[()|.,/ ]#_#g' -i all_contigs.fa
  # remove empty lines
  sed '/^$/d' -i all_contigs.fa

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Convert SIF file to sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (72) bind mounts
  /bin/bash: .command.sh: No such file or directory
  INFO:    Cleaning up image...
```
## Environment 
Nextflow 20.01.0 (WtP-intended), **standard** exec. profile, *empty* .command.out in the process work dir and .command.sh **is** in the work dir.

**Comment by replikation** [comment]
hi, thanks for writing an issue 
* can you please provide the full nextflow command that you used?

**Comment by stefanches7** [comment]
From `byobu` I launched
`./nextflow ../What_the_Phage/phage.nf --fasta /s/project/phagehost/data/all_contigs.fa --workdir /s/project/phagehost/workdir --databases /s/project/phagehost/dbs --cachedir /s/project/phagehost/c --mp`

**Comment by replikation** [comment]
I assume its about the singularity execution?
* did you forgot the `-profile lsf` flag? or what config are you using?
* we don't have a `--databases` flag
* which branch are you using? master?

**Comment by replikation** [comment]
.command.sh  is the "script" file that nextflow is generating to execute the process. This is located in your "workdir".

Might be related to [this](https://github.com/nextflow-io/nextflow/issues/73) ?

"The error happens when the run folder is not in /Users."

**Comment by hoelzer** [comment]
@stefanches7 I think you are trying to execute WtP locally now (not in the cluster environment), right? 

First of all, the parameters ``--cachedir`` and ``--databases`` are only used when executing the pipeline on HPC. You can pass them, but they will just not have any effect. For example, I used the current ``slurm`` branch with this command to somehow reproduce your execution:

```bash
nextflow phage.nf --fasta test-data/POI_draft.fa --workdir work --databases dbs --cachedir cache --mp
```

Because I did not assign any ``-profile`` the _standard_ one is used with Docker support. Databases are stored in ``nextflow-autodownload-databases``. The command above was working for me. 

I agree with @replikation that this might be a Docker configuration issue?

**Comment by stefanches7** [comment]
@stefanches7 probably - might be that our `docker` is just a mock. Singularity works with the same command, so I'm closing the issue. Thanks!
