### ISSUE TITLE
Skip-Phage-Identification

### ISSUE THREAD

**Issue by mult1fractal** [replikation/What_the_Phage#68]
* People might just want to annotate the genes in the Sequence because they already know their Sequence is a Phage-sequence.
* flag to skip Identification tools (--annotate) and use input of user as input for annotation of genes in phage sequence

**Comment by mult1fractal** [comment]
* adding clean skipping flags for skipping:
  * identification only
  * annotation only
  * tax only
* by default: execute whole workflow

**Comment by replikation** [comment]
not sure about the tax currently. but the anno or identy only sounds good

**Comment by replikation** [comment]
* implemented
