### ISSUE TITLE
checkV-

### ISSUE THREAD

**Issue by mult1fractal** [replikation/What_the_Phage#70]
* [CheckV](https://bitbucket.org/berkeleylab/checkv/src/master/)

* fully automated command-line pipeline for assessing the quality of metagenome-assembled viral genomes, including identification of host contamination for integrated proviruses, estimating completeness for genome fragments, and identification of closed genomes.

* working commands:
```shell
checkv completeness T7_draft/phage_positive_contigs/T7_draft_positive_contigs.fa -d ../DB/checkv-db-v0.6 -t 30 results
checkv repeats T7_draft/phage_positive_contigs/T7_draft_positive_contigs.fa  results
checkv contamination T7_draft/phage_positive_contigs/T7_draft_positive_contigs.fa -d ../DB/checkv-db-v0.6 -t 30 results
```

* based on three commands above: generates summary file
```shell
quality_summary T7_draft/phage_positive_contigs/T7_draft_positive_contigs.fa  results
```

Output:
```shell
contig_id contig_length genome_copies gene_count viral_genes host_genes checkv_quality miuvig_quality completeness completeness_method contamination prophage termini
ctg1_len=102949 102949 1.01 161 109 0 High-quality High-quality 100.0 AAI-based 0.0 No NA
ctg2_len=44018 44018 1.0 70 11 0 Not-determined Genome-fragment NA NA 0.0 No NA
ctg3_len=25734 25734 1.0 55 27 0 Not-determined Genome-fragment NA NA 0.0 No NA
ctg4_len=21924 21924 1.0 24 8 0 Not-determined Genome-fragment NA NA 0.0 No NA
ctg5_len=16494 16494 1.0 10 0 0 Not-determined Genome-fragment NA NA 0.0 No NA
ctg6_len=5303 5303 1.0 5 2 0 Not-determined Genome-fragment NA NA 0.0 No NA
```

* extend with tools  e.g. virnet hit  yes/no
* extend table via .join (channelhandling training) --- .join Taxonomic classification from sourmash  
* --> nice overview table :)

* possible pro phage tool?

* should be rdy for Release -r v0.7

**Comment by replikation** [comment]
`nanozoo/checkv:0.4.0--f3ed06e`

**Comment by replikation** [comment]
* implemented
