### ISSUE TITLE
Some other tools to include?

### ISSUE THREAD

**Issue by sxh1136** [replikation/What_the_Phage#75]
I've been compling a list of phage tools for something I'm writing and came across this GitHub. This looks really exciting and I look forward to trying this out. 

I think there might be some tools on my list that you haven't come across or at least haven't put down yet like Cenote-Taker2 or metaViralSPAdes?

Here's my list of phage tools for metagenomes and metaviromes:
https://github.com/sxh1136/Phage_tools

**Comment by replikation** [comment]
* thank you very much, this is really helpful
* due to our modular coding approach we can easily add these tools to our workflow which is the point/goal of WtP either way :)
