### ISSUE TITLE
Ability to enable 'virome' mode for tools: VirSorter + VIBRANT (and others?)

### ISSUE THREAD

**Issue by mshamash** [replikation/What_the_Phage#81]
Hello,

Thank you for making this Nextflow pipeline, it's really a great resource to have!

Something I noticed when doing some preliminary work with WtP so far is that there is no user-facing option to enable the 'virome' modes associated with some tools. For example, VirSorter calls it 'virome decontaination' mode and the flag is `--virome`, whereas VIBRANT calls it virome mode and the flag is `-virome`.

Without these flags, these tools assume that we are using a native metagenome as input (which may be the case sometimes, but not all the time for all users) and this could severely affect tool sensitivity and output.

I'm not sure if any other of the included tools have a similar flag, as I am most familiar with VirSorter and VIBRANT. If they do, it may be worth adding as well. Ideally, one Nextflow flag such as --virome would flip "ON" virome mode for all these different tools.

An additional point for VirSorter, it may be useful to have a flag to specify which database to use, since they have both Viromes and Refseq databases included. By using `-db 1` which WtP does now, it defaults to the RefSeq database. `-db 2` flag is for Viromes and contains RefSeq and more viral sequences on top of that. 

Cheers.

Michael

**Comment by replikation** [comment]
* ah thank you very much for bringing this to our attention 
* a `--virome` flag seems like the best choice, we take a look how to implement this
   * same for the database

**Comment by replikation** [comment]
@mult1fractal I'll add this to the v0.8 as its either way part of the parameter optimizations

**Comment by mshamash** [comment]
> * ah thank you very much for bringing this to our attention
> * a `--virome` flag seems like the best choice, we take a look how to implement this
>   
>   * same for the database

Thanks! On another note, I’ll take this opportunity to ask what the plans are for prophage prediction? Many of these tools also output prophage predictions too. It’d be great to one day be able to input a bacterial genome and get all the predicted prophages by all the tools as output.

**Comment by replikation** [comment]
yep we are currently looking into this, WtP predicts already prophages - as some tool report them of course (which are then also labelled by the checkV table results as such)
* but we want to implement this in a clean way with clear outputs, that why it's currently not "officially" supported - also there are some tools specifically designed for prophages that we want to include for this
* we currently have prophages included in milestone [v0.9](https://github.com/replikation/What_the_Phage/milestone/3)
  * you can also add comments here https://github.com/replikation/What_the_Phage/issues/73 if you like regarding ideas/suggestions

**Comment by hoelzer** [comment]
Indeed, good and important suggestions, @mshamash ! 

@replikation @mult1fractal you might want to have a look here bc/ we also implemented `--virome` mode for VirSorter in VIRify:
https://github.com/EBI-Metagenomics/emg-viral-pipeline/blob/master/nextflow/modules/virsorter.nf

But yeah, it's really just a switch adding `--virome` or not. 

and we are using`-db 2` as a default but I am not sure what actually is the best default for most data sets. However, making this an adjustable user input for experienced runs makes totally sense.
