### ISSUE TITLE
Command 'ps' required by nextflow to collect task metrics cannot be found when running '-with-tower'

### ISSUE THREAD

**Issue by peterk87** [replikation/What_the_Phage#89]
When I try to run WtP with [Nextflow Tower](https://tower.nf/) enabled (running Nextflow with `-with-tower` flag), the `ps` isn't found in the Docker containers and seems like it's needed for collecting task trace info. With Nextflow Tower disabled, the workflow runs without issue. I think the same issue may surface with [Nextflow weblog](https://www.nextflow.io/docs/latest/tracing.html#weblog-via-http) but I haven't confirmed.

When trying to run the following command:

```bash
$ nextflow run replikation/What_the_Phage \
    -profile local,docker \
    --cores 64 \
    --filter 500 \
    --output WtP-results \
    --workdir WtP-work \
    --fasta 'megahit-fastas/*.fasta' \
    -r v0.8.1
```

I get the following error:

```
Error executing process > 'vibrant_database:vibrant_download_DB'

Caused by:
  Process `vibrant_database:vibrant_download_DB` terminated with an error exit status (1)

Command executed:

  # profile names for VIBRANT_setup.py
  cp -r /opt/conda/share/vibrant-1.0.1/databases/profile_names .
  /opt/conda/share/vibrant-1.0.1/databases/VIBRANT_setup.py

  # pack together database
  mkdir database && mv *.{HMM,h3?} database
  cp /opt/conda/share/vibrant-1.0.1/files/VIBRANT*.{tsv,sav} database
  tar -czf database.tar.gz database/

Command exit status:
  1

Command output:
  (empty)

Command error:
  Command 'ps' required by nextflow to collect task metrics cannot be found
```

I've also tried the `singularity` profile with Singularity (v3.5.3).

It doesn't look like `ps` is found in the Docker container:

```bash
$ docker run -it multifractal/vibrant:0.4
(base) root@39e7800b548e:/# ps
bash: ps: command not found
```

---

### Potential Solution

Add `apt install procps` to the `Dockerfile` for `multifractal/vibrant`. It looks like `procps` is installed in some of the other containers already.

https://github.com/replikation/What_the_Phage/blob/f6f10caaf486112ec2d54910fb7acc71bf02b4ca/phage-tool-Dockerfiles/DeepVirFinder/Dockerfile#L5 

---

### System Info

- OS: Ubuntu 18.04 LTS
- Nextflow version: 20.07.1
- Docker version: 19.03.6, build 369ce74a3c

**Comment by replikation** [comment]
hi,

thanks for the interest in WtP. We will check all or container and update the ones without `procps`. Thanks for reporting, as tower is quite convenient this will be fixed.

**Comment by replikation** [comment]
@mult1fractal please check your containers too, we add this to `v0.8.2` so it can be directly used.

**Comment by mult1fractal** [comment]
@peterk87 : we added procps to all dockerfiles 

The following command should work now in release v0.8.2:
```shell
nextflow run replikation/What_the_Phage \
    -profile local,docker \
    --cores 64 \
    --filter 500 \
    --output WtP-results \
    --workdir WtP-work \
    --fasta 'megahit-fastas/*.fasta' \
    -r v0.8.2
```
