### ISSUE TITLE
Filter Results from tools for further application (smatools, taxonomy, heatmap)

### ISSUE THREAD

**Issue by Stormrider935** [replikation/What_the_Phage#9]
### Metaphinder

Output from tool:
>contigID	classification	ANI [%]	merged coverage [%]	number of hits	size[bp]
ctg1	phage	75.357	99.967	71	77616
ctg2	phage	12.049	16.991	61	45788
ctg3	phage	61.742	83.422	80	56341
ctg4	phage	75.595	99.995	55	18684
ctg5	phage	54.507	72.777	12	11233
ctg6	phage	58.68	78.916	32	10420
ctg7	phage	71.843	95.827	47	11046
ctg8	phage	51.998	67.979	14	8713
ctg9	phage	75.518	99.99	52	9716
ctg10	phage	74.659	98.796	47	8641

```shell-script
export LC_NUMERIC=en_US.utf-8
###### print contig only ########
 mkdir sorted_contig_only
 sort  -g  -k4,4 *.txt | awk '$2>=phage' | awk '{ print $1 }' | tail -n+2 > sorted_contig_only/sorted_contig_only.txt

```

output filterscript :  sorted_contig_only.txt

ctg7
ctg11
ctg10
ctg14
ctg1
ctg9
ctg4

printed contigs classified as 'phage' in neue file

**Comment by replikation** [comment]
@Stormrider935 status? this can be closed or? please ref the commits
