### ISSUE TITLE
Required storage space?

### ISSUE THREAD

**Issue by ponchorox** [replikation/What_the_Phage#91]
I was running your sample script and my own test sample with very limited functions and on both occasions I found my testing SSD was filling up before concluding anything (120GB admitedly small). Aside from the downloadeable database, what else is being created that fills up so much space? Seems like too much, even in the second test run I was only using VIBRANT and annotate flags and it still filled up, what does a full test run end up looking like in terms of storage? (I would like to know before moving this to a server)

**Comment by hoelzer** [comment]
Hi,

thanks for writing the issue. Besides the databases that are per default
writen to your current directory the pipeline is executed from, WtP writes
temporary files to `/tmp`.

Could it be that your `/tmp` disk space is limited?

You can also try to point the temporary files to another location via
`--workdir`.

ponchorox <notifications@github.com> schrieb am Mo., 3. Aug. 2020, 00:18:

**Comment by replikation** [comment]
yes as @hoelzer pointed out temporary file location can be modified via `--workdir`

please see also the documentation on [Data handling](https://github.com/replikation/What_the_Phage#Data-handling)

**Comment by ponchorox** [comment]
"Could it be that your `/tmp` disk space is limited?"
It is.
Given that there are a few users who have to do some explaining to their admin if they are running a new script, I think it would be appropiate to know the expected size of both results and tmp folder. I understand it would depend on which and what flags are active and the input but having a rough estimate of let's say the example test run provided in the documentation may not only be useful but something they need to know for certain users.

**Comment by replikation** [comment]
* we will check that and add the information to the readme for the approx size of the "test run" but in the end its completely depended on the user input, the bigger the input the bigger the tmp files
* if tmp is limited use `--workdir path1/path` to point the tmp directory to another location of your choice 
* e.g. if space is an general issue attach an external drive and point these flags to that disk:
   * we added all these flags so the user can point everything to disks with enough space
````
--workdir /path/to/dir    # defines the path where nextflow writes temporary files, default: '/tmp/nextflow-phage-$USER'
--database /path/to/dir   # specify download location of databases, default './nextflow-autodownload-databases'
--cachedir /path/to/dir   # defines the path where singularity images are cached, default './singularity-images'
--output results 
````
