### ISSUE TITLE
Running WTP on multiple nodes

### ISSUE THREAD

**Issue by gabriellovate** [replikation/What_the_Phage#96]
Is it possible to run WTP on a cluster managed through SLURM  in multiple nodes or the pipeline only manages processes in a single node? I couldn't clearly understand how to accomplish this based on the available documentation.

**Comment by replikation** [comment]
WtP (or nextflow) submits each process in parallel for jobs that can be run in parallel to slurm if you start the workflow via e.g. `-profile slurm,singularity` . Your slurm installation then manages the workload/node distribution, so yes it should use multiple nodes/available resources

**Comment by gabriellovate** [comment]
Okay, so in that case there is no need to specify - cores when sending the command? 
I would also like to register my compliments for the tool and for your accessibility in requests.

**Comment by replikation** [comment]
* each process ist pre-configured by us regarding ram and cpu for HPC or cloud computing in [this file](https://github.com/replikation/What_the_Phage/blob/master/configs/node.config)
* and slurm also [here](https://github.com/replikation/What_the_Phage/blob/caa8540ce14c050ed6e20aafe1d1967e349a3592/nextflow.config#L92)

**Comment by gabriellovate** [comment]
Now it's much clearer for me ^^
Thank you for your support!
