### ISSUE TITLE
Have a smaller test case

### ISSUE THREAD

**Issue by phiweger** [replikation/What_the_Phage#97]
Ideally, it should be possible to run WtP in max 10 mins on some (truncated?) test contig -- anything longer is not a test but an adventure ;)

**Comment by replikation** [comment]
* small test data is available [here](https://github.com/replikation/What_the_Phage/tree/master/test-data) but yes we add a `smalltest` profile option using on of these files

**Comment by replikation** [comment]
* but the first-time download will probably take like 10 mins already ;)
